### ISSUE TITLE
User dropdown issue in UserNav panel pattern

### ISSUE THREAD

**Issue by dsahu75** [Esri/calcite-web#1001]
The User dropdown is not visible fully since it is displayed behind  the code snippet in the usernav panel.
http://esri.github.io/calcite-web/documentation/patterns/#user-nav

Also the Sign In link and Sign Up buttons are misaligned in User Sign In 
http://esri.github.io/calcite-web/documentation/patterns/#user-sign-in

**Comment by macandcheese** [comment]
Doing some issue cleanup - this functionality is probably better found / discussed @ https://github.com/Esri/global-nav for now, going to close this issue.
