### ISSUE TITLE
Loader animation issue on Safari

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#1004]
The "pulse" animation for the loading indicator doesn't respect height correctly after initial animation.

![screen shot 2019-01-07 at 9 33 36 am](https://user-images.githubusercontent.com/4733155/50783337-5f34ce00-125f-11e9-8263-febb7866c35c.png)

**Comment by paulcpederson** [comment]
thanks, _Safari_

**Comment by macandcheese** [comment]
Closing, will be added in CC.
