### ISSUE TITLE
Update quickstart guide

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1007]
1. Getting the CSS pulled in
1. Setting up the global-nav
1. using some non-interactive components/patterns
1. using some interactive calcite-components
1. using some calcite-ui-icons

**Comment by paulcpederson** [comment]
Moving this back to the backlog. It will be easier to write this with new screenshots once all the components/patterns are written

**Comment by julio8a** [comment]
We don't need this guy anymore.
