### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1013]

**Comment by macandcheese** [comment]
Modals will now have additional opt-in classes:

- "statused" modals for information or destructive actions that can be combined with a regular modal or any of the below (except page takeover)
- "sheet" modals that dock at the bottom of screen on mobile and are constrained with a max-height
- "page takeover" modals that take the full page height and width, with a max width that reveals content behind at large breakpoints, and
- "page takeover no constraint" that doesn't have a max width, useful for maps or other content-rich uses.

The structure of modal markup will change to provide distinct header, footer, and content sections to better facilitate content scrolling and docking on smaller screens.

**Comment by julio8a** [comment]
closing this out since it's also moving to calcite-components: [modals](https://github.com/ArcGIS/calcite-components/issues/9)
