### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1019]
- `btn-transparent`should still have the 1px border transparent so it doesn't jump up 1px. Keeping text aligned with primary and secondary buttons if they live side by side.

**Comment by macandcheese** [comment]
Thoughts on deprecating the 'btn-disabled' class? I know we've had discussions on the appropriateness of its use.

It would be a breaking change but now would be the time to remove it and maybe suggest an alternative best practice.

@mitc7862 @paulcpederson @julio8a @bstifle

**Comment by julio8a** [comment]
@macandcheese, any suggestion on alternatives?

I'm hesitant on applying to the default anchor tag. As there can be cases where the underline might not be fitting? In the past, we use to have a few HTML tags have Calcite styling, but people requested to remove and be a class option for styling.

**Comment by bstifle** [comment]
im fine with whatever. no skin in this game for me

**Comment by julio8a** [comment]
Implemented in calcite-components:
https://github.com/Esri/calcite-components/issues/71
