### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1022]

**Comment by paulcpederson** [comment]
new component implementation will hopefully address this safari bug with current loader: #1004

**Comment by julio8a** [comment]
[Loaders-Squares.mp4.zip](https://github.com/Esri/calcite-web/files/3118863/Loaders-Squares.mp4.zip)

**Comment by julio8a** [comment]
This component is also moving over to calcite-components: [loader](https://github.com/ArcGIS/calcite-components/issues/7). Closing this out.
