### ISSUE TITLE
Checkboxes & Radio Buttons

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1030]

**Comment by julio8a** [comment]
Currently there are many variations of checkboxes... 

This is ArcGIS Online along:
![image](https://user-images.githubusercontent.com/6144462/51285651-8ba9c200-19a4-11e9-8986-8c265fad388d.png)

**Comment by julio8a** [comment]
Here is the checkbox and radio box design by Mitch:

![image](https://user-images.githubusercontent.com/6144462/51285860-5651a400-19a5-11e9-984c-aa1e34ed2ca0.png)

**Comment by macandcheese** [comment]
Should address https://github.com/Esri/calcite-web/issues/1074

Also @mitc7862 these are the same style as what's currently in the category assignment page takeover correct?

**Comment by mitc7862** [comment]
@macandcheese I believe any resemblance is coincidental

**Comment by julio8a** [comment]
this is moving to calcite-components (https://github.com/ArcGIS/calcite-components/issues/1), closing this out.
