### ISSUE TITLE
Doc for Forms should read "colon" instead of "semicolon"

### ISSUE THREAD

**Issue by jpeterson** [Esri/calcite-web#1053]
The second sentence in the documentation for Forms mentions not following labels with a semicolon, but should say **colon**:

>Labels for form elements should describe what the field is. Labels should not be followed by a ~semicolon~ colon.

http://esri.github.io/calcite-web/documentation/components/#forms

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-web/pull/1054
