### ISSUE TITLE
Radio Buttons are pixelated in Firefox on Windows

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#1074]
Looks like setting the size of radio buttons this large is causing strange rendering for Firefox on windows machines.

We may just be able to reduce the size of the radio button elements to eliminate this pixelation.

![e2870100-5176-11e9-96d4-9fdd1b350bd5](https://user-images.githubusercontent.com/1031758/55200814-38f73e00-517d-11e9-84f7-7c772e7ea162.png)

**Comment by macandcheese** [comment]
Closing this.
