### ISSUE TITLE
Support expanding multiple accordions when same link is in both accordions

### ISSUE THREAD

**Issue by lheberlie** [Esri/calcite-web#1077]
We have cases where a sample in the JavaScript SDK https://js.arcgis.com will exist in the "Latest Samples" accordion and also exist in another section.

Here was the original question:

> Could we figure out a way to open the sample folder entry point that was clicked?

**Comment by macandcheese** [comment]
Hi @lheberlie - doing some issue cleanup, apologies for the radio silence. It looks like maybe the link you provided has changed as I don't see an accordion there?

We have a new component library - Calcite Components - that includes an updated accordion: https://esri.github.io/calcite-components/?path=/story/accordion--simple

The updated component may resolve your issue, and if not, feel free to file a new issue at the Calcite Components repo: https://github.com/Esri/calcite-components
