### ISSUE TITLE
Console Uncaught TypeError

### ISSUE THREAD

**Issue by jsavella** [Esri/calcite-web#1080]
Error is encountered when the "Esc" key is pressed. 

Complete Msg
Uncaught TypeError: Cannot ready property 'getAttribute' of undefined .     calcite-web.min.js:7
at f (calcite-web.min.js:7)
at calcite-web.min.js:7
at u.emit (ccalcite-web.min.js:7)
at HTMLDocument.<anonymous> (calcite-web.min.js:7)

**Comment by macandcheese** [comment]
Hi @jsavella - could you provide a little more context around this issue? Are you encountering this with a specific pattern or component?

**Comment by paulcpederson** [comment]
Are you on the latest version? I fixed an unhandled error event a couple releases back, so if you're not would be good to upgrade and try again.

**Comment by macandcheese** [comment]
This project is deprecated, closing this issue.
