### ISSUE TITLE
Allowing scroll in Accordion content

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-web#1105]
I am needing to have an accordion expand to a specified height or the container's height and allowing the `accordion-content` to be scrollable.

Presently, the accordion does not seem to allow scrolling in the content. Instead, the whole accordion scrolls within the parent container. I'm needing a way to prevent this from happening. Additionally, I am rendering a component/widget inside the `accordion-content`. Also, the accordion header does not stay at the top. 

Is there a way to accomplish this?

Below is a screenshot of the behavior:

_scrolled to top:_
![image](https://user-images.githubusercontent.com/17069279/62476457-0980bf80-b775-11e9-9eb2-cd81e43a57c6.png)

_scrolled down:_
![image](https://user-images.githubusercontent.com/17069279/62476795-b2c7b580-b775-11e9-959d-974da906a882.png)

**Comment by macandcheese** [comment]
Hi @tyanthony - apologies for the radio silence. We have a new component library - Calcite Components - that includes an updated accordion component. You should be able to constrain any components you put inside with your own styling, although the provided headers currently do not "stick" to the top (if I'm interpreting your question correctly). 

You can see a demo here: https://esri.github.io/calcite-components/?path=/story/accordion--simple

And if the issue still occurs, feel free to open an issue in the Calcite Components repository: https://github.com/Esri/calcite-components 

Thanks!

**Comment by macandcheese** [comment]
Closing based on above comment.
