### ISSUE TITLE
Unique grid classes to prevent collisions with other libraries

### ISSUE THREAD

**Issue by jhough10** [Esri/calcite-web#332]
Is there a way that we can define a more unique class structure for the grid?

Current:
```
<div class="grid-container">
    <div class="column-24">
        <blockquote>Contain the Columns</blockquote>
    </div>
</div>
```

Suggestion:
```
<div class="calcite-grid-container"> or <div class="c-grid-container">
    <div class="calcite-column-24"> or <div class="c-column-24">
```

Concern is that with the basic `column-24` two libraries might use the same pattern and would cause issues.

Thanks.

**Comment by paulcpederson** [comment]
Reopening as this doesn't actually work. Looks like we left the main column selector as `column-` with no reference to the `$prefix` variable. So if there is a naming collision (which has actually come up a couple times) this would not fix the collision.

Need to add `${prefix}column` as the main selector. Also, as far as I can tell this feature is undocumented? So we should add a line to http://esri.github.io/calcite-web/documentation/grid/#configuration that explains how to do this.

**Comment by jhough10** [comment]
@paulcpederson good catch!

**Comment by nikolaswise** [comment]
@paulcpederson looks like this is the trouble?

```
 [class*="column-"] { @include column(); }
```

**Comment by paulcpederson** [comment]
yes, that is what I'm referring to. Should be `[class*="${prefix}column-"] { @include column(); }`

**Comment by paulcpederson** [comment]
Also playing around with just assigning default column styles to all the columns via extension locally. It adds 24 selectors, but they are not gross and generic, and also they would be much faster. @nikolaswise do you have thoughts on that?

**Comment by nikolaswise** [comment]
@paulcpederson only 24? That's probably within budget.
