### ISSUE TITLE
Consider another pass on typography?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#489]
Inspired by a recent read of http://typecast.com/blog/a-more-modern-scale-for-web-typography and https://github.com/ArcGIS/arcgis-for-developers/issues/3514 should we make another pass to tighten up typography? Especially on mobile? Some ideas include:

1. More contrast between `font-size`, especially in the h1-h3 range.
2. Consider `font-weight: 400` for h1 and h2
3. Responsive scale for readable line lengths across screen sizes.

**Comment by nikolaswise** [comment]
I'll play with this today!`

**Comment by nikolaswise** [comment]
Responsive type scale is an interesting idea that I might explore. Might be harder to keep it clean and tidy without a huge amount of magic-number type css selectors, but I'll see what I can do.

**Comment by nikolaswise** [comment]
Responsive checks added to switch scales on screen size - smaller screen sizes use less extreme scales. 

![screen shot 2016-03-18 at 11 55 48 am](https://cloud.githubusercontent.com/assets/1987772/13888781/8776dbec-ed00-11e5-846f-9325a6ab2fa9.png)
![screen shot 2016-03-18 at 11 56 03 am](https://cloud.githubusercontent.com/assets/1987772/13888780/87765dfc-ed00-11e5-9c9f-bd358f84c022.png)
![screen shot 2016-03-18 at 11 55 58 am](https://cloud.githubusercontent.com/assets/1987772/13888779/87762ae4-ed00-11e5-8304-00bc0bc2bcc3.png)

**Comment by nikolaswise** [comment]
This is in master! And it's great.
