### ISSUE TITLE
Input validation styles

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#500]
We should provide some basic styles for `:valid` and `:invalid` states of form fields. Here is some work that was done speccing some of this out:

![screen shot 2016-03-23 at 5 59 32 pm](https://cloud.githubusercontent.com/assets/1031758/14005540/8c19559c-f121-11e5-9c94-f7e1eb29a05e.png)
![screen shot 2016-03-23 at 5 59 39 pm](https://cloud.githubusercontent.com/assets/1031758/14005543/8c1ace36-f121-11e5-8d9f-8ba371738d21.png)
![screen shot 2016-03-23 at 5 59 43 pm](https://cloud.githubusercontent.com/assets/1031758/14005545/8c1bdb50-f121-11e5-9412-897c35f24198.png)
![screen shot 2016-03-23 at 5 59 48 pm](https://cloud.githubusercontent.com/assets/1031758/14005542/8c1a9d9e-f121-11e5-80ed-31f9b52e575a.png)
![screen shot 2016-03-23 at 5 59 53 pm](https://cloud.githubusercontent.com/assets/1031758/14005544/8c1b6bfc-f121-11e5-8bab-2995b04d4ca2.png)
![screen shot 2016-03-23 at 5 59 57 pm](https://cloud.githubusercontent.com/assets/1031758/14005541/8c195b50-f121-11e5-9168-f1e5fb5dea1d.png)

**Comment by paulcpederson** [comment]
:tada:   500 Issues!   :tada:

**Comment by asangma** [comment]
Sounds like my last relationship.

**Comment by paulcpederson** [comment]
*zing*

**Comment by nikolaswise** [comment]
http://codepen.io/boast/pen/pLjld

Has some nice stuff - some caveats that might bite us.

**Comment by paulcpederson** [comment]
Isn't that codepen demo the opposite of this issue? It hijacks validation for "floating labels".

**Comment by nikolaswise** [comment]
@asangma ^

**Comment by nikolaswise** [comment]
Okay, matched the first spec in #538
