### ISSUE TITLE
Pin sub-nav title a bit smaller

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#504]
I think the `type` branch will probably address this and/or change the scale, but the new scale makes `h1`s larger (good). Except in a `sub-nav` it's a little too large, so we should add a `font-size` declaration to `sub-nav-title`.

**Comment by paulcpederson** [comment]
<img width="1315" alt="screen shot 2016-03-25 at 9 03 21 pm" src="https://cloud.githubusercontent.com/assets/1031758/14057971/8579946a-f2cd-11e5-92d8-1168b0a40b4c.png">

**Comment by nikolaswise** [comment]
Agreed. Addressing in type branch.

**Comment by nikolaswise** [comment]
fixed in #508
