### ISSUE TITLE
Textareas render as monospace in Firefox

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#505]
I think this is just a matter of actually setting `font-family` on `textarea` to `inherit`
<img width="1006" alt="screen shot 2016-03-26 at 12 43 41 pm" src="https://cloud.githubusercontent.com/assets/1031758/14062105/adcddd3a-f350-11e5-9dfb-484d5ee5cb7b.png">

**Comment by nikolaswise** [comment]
That seems to do the trick. Will be in type PR

**Comment by nikolaswise** [comment]
fixed in #508
