### ISSUE TITLE
Need a way to unbind sticky/scroll events

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#506]
Need an event to remove the scroll listener. ie if you have a button on the screen that is sticky, and then it is removed, the scroll handler will throw errors not being able to find it:

<img width="963" alt="screen shot 2016-03-26 at 12 51 19 pm" src="https://cloud.githubusercontent.com/assets/1031758/14062133/7b312d86-f351-11e5-98a6-40b4d78740b2.png">

**Comment by nikolaswise** [comment]
The only thing being bound is the scroll event - unbinding this would make all stickies stop, not just the one that is removed from the dom. 

Solution is to add checks - make sure that dom even exists before moving on.

# 510

**Comment by paulcpederson** [comment]
wooord
