### ISSUE TITLE
block class inside block-group now renders in monospace

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#507]
the `.block` class needs the Avenir declaration, maybe it got removed? From /page-layouts/homepage/ 

<img width="1126" alt="screen shot 2016-03-26 at 12 57 08 pm" src="https://cloud.githubusercontent.com/assets/1031758/14062161/69d84d98-f352-11e5-894a-399f7ad87bda.png">

**Comment by nikolaswise** [comment]
fixed in #508
