### ISSUE TITLE
.link-external helper class

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#527]
It would be nice to be able to style links and buttons with a class that would add an icon to make then external links.

![window](https://cloud.githubusercontent.com/assets/378557/14218848/b19048e4-f80b-11e5-8c0d-fa062398cba0.png)

Possible uses:

* Open In ArcGIS Online/Open in Map Viewer/Open Service in the developers site
* Referencing external docs like Dojo or MDN in the JS API pages
* Ect...

**Comment by paulcpederson** [comment]
does `.icon-ui-link-external` not work?

**Comment by nikolaswise** [comment]
@patrickarlt closing this issue. reopen if `.icon-ui-link-external` isn't a thing that works.
