### ISSUE TITLE
Some elements wrap in rtl

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#532]
Not sure why but several elements wrap to two lines when in right to left?

![screen shot 2016-04-06 at 12 00 58 pm](https://cloud.githubusercontent.com/assets/1031758/14329223/44997e8a-fbef-11e5-8fb9-3388c9d6d69a.png)
![screen shot 2016-04-06 at 12 01 02 pm](https://cloud.githubusercontent.com/assets/1031758/14329224/449a59a4-fbef-11e5-8e31-e44e7a093c26.png)

`sub-nav` and `top-nav-title`. there may be more, looks like `white-space: nowrap;` fixes it?

**Comment by nikolaswise** [comment]
Fixed in #535
