### ISSUE TITLE
pre-X and post-X classes break layouts in right to left on larger screens

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#533]
past the largest break point, the post is calculated incorrectly on right ot left, leading the column to not have enough room and jump down:

![screen shot 2016-04-06 at 12 10 20 pm](https://cloud.githubusercontent.com/assets/1031758/14329525/849d0b4a-fbf0-11e5-825e-34d771d14267.png)

**Comment by nikolaswise** [comment]
#535 fixes this for large screens. Although the problem of pre and post on one element in RTL still exists

**Comment by paulcpederson** [comment]
let's open a new issue for that.
