### ISSUE TITLE
Radio and checkbox classes causing naming collisions

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#541]
The chances that existing projects will have something with a class of `radio` or `checkbox` is pretty high. Currently causing some collisions in portal app. 

I think maybe we should change this to something like `fieldset-checkbox` and `fieldset-radio` as this class actually goes on the fieldset. 

Additionally we should declare the base styles for the fieldset regardless if you've used one of these classes so that `fieldsets` are actually styled.

**Comment by nikolaswise** [comment]
@paulcpederson wasn't styling base `fieldsets` what was originally causing collisions with legends?

**Comment by paulcpederson** [comment]
No the `fieldset label` selector was the problematic one.

**Comment by nikolaswise** [comment]
yeah. Changing to always style `fieldset` and only style `.fieldset-checkbox label`

**Comment by nikolaswise** [comment]
Done in #543
