### ISSUE TITLE
Vertical Half scroll slider/carousel

### ISSUE THREAD

**Issue by mpalmeresri** [Esri/calcite-web#544]
I'm working through some component concepts for the esri.com redesign and looking to build a slider that will use the natural gesture of scrolling to reveal content in each slide, as opposed to clicking to reveal content. Specifically, this is to accomplish a light product demo where key screens can be showcased in an interactive way without heavy video or embedded maps.

Something like this:
http://alvarotrigo.com/multiScroll/#first

But with variations for transitions between content on the left that feels more like a fade ease/in and less like a solid chunk.

We have done something similar with ArcGIS Earth and the laptop screen, but the 1/2 screen scroll is a component I can see being used in multiple situations.

Also attached a quick sketch of the component and a brief about the use.
[product-demoCROP.pdf](https://github.com/Esri/calcite-web/files/218041/product-demoCROP.pdf)

---

This will need some refinement and variations so I anticipate plenty of follow-up and clarifying questions.

Matt

**Comment by nikolaswise** [comment]
Added a couple more animation classes to deal with this. Combing classes like `animate-fade-in` with `animate-slide-down` will fade and drop a DOM node in. Animation details can be tweaked and finalized in future issues if needed, but the basics are there. 

To build your thing, use:

> http://esri.github.io/calcite-web/javascript/#event-bus
Listen to the `scrolling:at` bus event to see if your node is in the viewport yet.

> http://esri.github.io/calcite-web/javascript/#dom-utilities
When it is, use `addClass(classname, node)` to add 

> http://esri.github.io/calcite-web/components/#animation
The relevant animation classes.

**Comment by hhkaos** [comment]
I have seen a one thing broken: [Marketing samples](http://esri.github.io/calcite-web/examples/marketing/).

And also when clicking any "View HTML" button it add some extra characters at the end of the textarea like `">`, sometimes `</header> ">` (without an opening tag `<header>`), etc.

Cheers!
