### ISSUE TITLE
Add pattern for less obtrusive mobile sub-nav

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#546]
Stacked subnav takes up a lot of space. It also forces people to use the stacked subnav at tablet or lower, because it's baked into the framework.

I think we should move to a `select` on mobile that goes to the url of the `option` value. Then we can use our explicit mobile show/hide classes and developers can make the call for when they want to move to the mobile nav:

```
<div class="grid-container">
    <h1 class="sub-nav-title leader-2">
      <a href="#" class="link-white">ArcGIS Runtime SDK for Qt</a>
    </h1>

    <select class="tablet-show select-full trailer-half">
      <option value="../documentation/" selected>Home</option>
      <option value="../guide/">Guide</option>
      <option value="../api-reference/">API Reference</option>
      <option value="../sample-code/">Sample Code</option>
      <option value="../forums/">Forum</option>
    </select>

  <nav class="sub-nav-list tablet-hide">
      <a class="sub-nav-link is-active" href="../documentation/">Home</a>
      <a class="sub-nav-link" href="../guide/">Guide</a>
      <a class="sub-nav-link" href="../api-reference/">API Reference</a>
      <a class="sub-nav-link" href="../sample-code/">Sample Code</a>
      <a class="sub-nav-link" href="#">Forum</a>
  </nav>
</div>
```

`select-full` class is the only added css. (It just adds `width: 100%`).

Probably should add a bit of JavaScript that listens to change events on the `select` and goes to the page as well.

**Comment by nikolaswise** [comment]
I like it. Implemented in #548
