### ISSUE TITLE
Disabled states for Buttons - no hover & focus states

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#549]
@nikolaswise @paulcpederson - Disabled states for buttons (when using btn-disabled ) should not have a hover & focus state.

cc-ed @snelsonux @HeathMeyette @asangma @julio8a

**Comment by nikolaswise** [comment]
The way that our composable styles are arranged (modular, one class that sets all buttons to disabled) this would create a significant amount of code with overly-specific selectors. Can you provide your reasoning for why this is needed?

To address what I imagine is the core issue, I added a `cursor: not-allowed;` style on disabled buttons, much like Foundation.

- http://foundation.zurb.com/sites/docs/button.html

**Comment by fgarofalo10** [comment]
ok... seemed that if a button is disabled, then it shouldn't interact with a person's mouse when the hover, or finger when they tap.
