### ISSUE TITLE
Upgrade from v1.0.0-beta.5 to v1.0.0-beta.6 causes "drawer" to close unexpectedly

### ISSUE THREAD

**Issue by lheberlie** [Esri/calcite-web#553]
When upgrading from `v1.0.0-beta.5` to `v1.0.0-beta.6` the off-canvas "drawer" pattern used primarily for top-level mobile navigation closes unexpectedly when clicking in the search box.

![screen shot 2016-04-25 at 6 07 15 pm-2](https://cloud.githubusercontent.com/assets/1824760/14823527/8420de0a-0b98-11e6-814d-bab4b4f63cab.gif)

#### Calcite web

http://esri.github.io/calcite-web/patterns/#drawers

![apr-26-2016 10-24-00](https://cloud.githubusercontent.com/assets/1824760/14823696/0e5fb276-0b99-11e6-94a9-8690157dc962.gif)

**Comment by nikolaswise** [comment]
@lheberlie good bug catch!

**Comment by nikolaswise** [comment]
Fixed in next release.
