### ISSUE TITLE
Give active tab state

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#556]
User testing revealed that some users were having trouble evaluating and understanding active state of tabs. Maybe we could move to `$lightest-gray` from `$off-white`

**Comment by fgarofalo10** [comment]
@paulcpederson - if I read that note correctly, why would an active state be a gray fill? 

why note have for the hover (as currently implemented
` background-image: linear-gradient(to top, transparent 94%, #0079c1 96%, #0079c1 100%); `

and for the tab is-active, have:
` background-image: linear-gradient(to top, transparent 94%, #56a5d8 96%, #56a5d8 100%); `


@asangma @snelsonux - other thoughts?

**Comment by snelsonux** [comment]
@paulcpederson @fgarofalo10 can one of you link to which tabs on Calcite Web this issue is referring to? is it these: http://esri.github.io/calcite-web/patterns/#tabs

**Comment by snelsonux** [comment]
if so, I think what @fgarofalo10 is proposing is a good solution...this way we don't need to rely on gray values and can leverage the already strong hover state pattern as the basis for the active state.

**Comment by fgarofalo10** [comment]
... @snelsonux right, I'm proposing have the hover state be a dark blue and the active state be a lighter blue (or visa-versa)

**Comment by snelsonux** [comment]
cool, I think that works

**Comment by nikolaswise** [comment]
@paulcpederson `lightest-gray` was too dark. Staying with `off-white`.

@fgarofalo10 @snelsonux This is a good idea in principle, but doesn't work on the screen very well.

![eugh](https://cloud.githubusercontent.com/assets/1987772/14864242/f45875b8-0c6d-11e6-97ff-bac8b18e0dea.png)
