### ISSUE TITLE
Icons for different platforms.

### ISSUE THREAD

**Issue by sanjibpanda** [Esri/calcite-web#561]
I am wondering whether we are going to add any icons for different platforms. For example: icon-ui-apple, icon-ui-android, icon-ui-windows-8, icon-windows-classic etc.

**Comment by paulcpederson** [comment]
@sanjibpanda we actually did this in an older CSS framework and we had to stop using them. Most of those are registered trademarks and there was some legal limitations to distributing/using them.

**Comment by sanjibpanda** [comment]
Ahh. Got it. Makes sense! 
Thanks @paulcpederson! We will convey the message to authors if they will look for similar icons while authoring content for Calcite specific sites.

**Comment by nikolaswise** [comment]
:+1:
