### ISSUE TITLE
Sass comipling error with version v1.0.0-beta.11

### ISSUE THREAD

**Issue by sanjibpanda** [Esri/calcite-web#569]
Recently, I upgraded to version v1.0.0-beta.11 and since than getting Sass compilation error. Please find the attached error screenshot for more details.

As per @bradleywertman 's suggestion I opened _form.scss and replaced extend with include which resolved the issue temporarily. 
```@extend avenir-regular();```
with 
```@include avenir-regular();```

![calcite-error](https://cloud.githubusercontent.com/assets/2974151/14930797/846640b4-0e1b-11e6-9c53-693fe11464ff.png)

**Comment by nikolaswise** [comment]
Upgrading to beta-15 will solve this problem: https://github.com/Esri/calcite-web/blob/master/CHANGELOG.md#fixed-1
