### ISSUE TITLE
tabs-transparent tab-title - tab titles shift when clicking between tabs

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#573]
tabs-transparent tab-title - tab titles shift when clicking between tabs. Issue only seems to occur with .tabs-transparent not the other modifier-classes 

@nikolaswise @paulcpederson

**Comment by nikolaswise** [comment]
Got this in #577

**Comment by fgarofalo10** [comment]
thanks @nikolaswise
