### ISSUE TITLE
Tabs translucent and dark issues

### ISSUE THREAD

**Issue by jhough10** [Esri/calcite-web#596]
1) when adding classes for padding and gutter adjustments to make the tab larger than default the `0.5rem` set, the bottom of the tab no longer connects with the active tab content. 

**Implementation**

![esri_cdn](https://cloud.githubusercontent.com/assets/514803/15484060/dbbc82fe-20ec-11e6-8e87-4489a954480c.png)

```
<div class="tab-title">
  <a class="js-tab font-size-1 padding-leader-1 padding-trailer-1 gutter-left-1 gutter-right-1 clearfix is-active">Tab Title</a>
</div>
```

2) With the default implementation of `tabs-translucent` and `tabs-dark` the hover state for the `is-active` tab ends up forcing a white background in both instances when it should be a darker transparency in the same manner as the non-active tabs.

**Implementation**

![fullscreen_5_23_16__1_50_pm](https://cloud.githubusercontent.com/assets/514803/15484142/6d53fd3c-20ed-11e6-98d3-dfa84cddedb0.png)

`<a class="tab-title js-tab is-active">Tab Title</a>`

3) Active state for tabs in dark state have extra borders present.

![esri_cdn](https://cloud.githubusercontent.com/assets/514803/15484212/c3c099a0-20ed-11e6-9a43-8663afe0f159.png)
![esri_cdn](https://cloud.githubusercontent.com/assets/514803/15484218/cadd0afc-20ed-11e6-997a-c9ab09154511.png)

**Comment by jhough10** [comment]
@nikolaswise Didn't you fix these already? I can take a look if not.

**Comment by nikolaswise** [comment]
I did not fix this already. The trouble seems to be coming from the box model, and the way your using padding bottom on the tab to connect the tab title to the tab section.

**Comment by jhough10** [comment]
@nikolaswise Okay. Will take a look at this one. Thanks.
