### ISSUE TITLE
input field validation

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#602]
why does a default state of a require input text field have a red border?

```
input:required:invalid {
    border-color: #de2900;
}
```

Having a form display to a person, who has yet to input information, and several input fields have a red border is not the experience we want.

Is there a way to only display the red border after an invalid value has been entered?

@nikolaswise @paulcpederson 
cc @bstifle @snelsonux @HeathMeyette @asangma

**Comment by paulcpederson** [comment]
This also bothers @nikolaswise and I. We are trying to use html5 validation for the inputs, but I think we may need to move to a JavaScript solution where we add the required class once the user has interacted with the input. It's not possible to use straight pseudo classes and select for an input that is required but hasn't been interacted with yet from CSS, see http://stackoverflow.com/questions/3617020/matching-an-empty-input-box-using-css

**Comment by nikolaswise** [comment]
This is gone in the current version of the framework.
