### ISSUE TITLE
Calcite Javascript issue with v1.0.0-beta.24

### ISSUE THREAD

**Issue by sanjibpanda** [Esri/calcite-web#612]
Calcite-web js is not working with version v1.0.0-beta.24. It is throwing following error.
"GlobalTypeError: global is undefined".

**Comment by sanjibpanda** [comment]
Note: This issue is reproducible if calcite is installed through NPM. It's working fine when I copy the javascript manually from zip folder (https://github.com/Esri/calcite-web/releases/download/v1.0.0-beta.24/calcite-web.zip)

**Comment by nikolaswise** [comment]
@sanjibpanda Can you provide more context of how your including the library in your application from the node modules folder? I have this version running fine in an app, and cannot repro.

**Comment by sanjibpanda** [comment]
Ah ok.. bit weird then. I installed calcite through npm as instructed. When I runs Grunt, it push a copy of calcite-web.js from node modules to my build/... folder from where I see the pages on browser. I was comparing the calcite-web.js (using node modules) from my app with the one I gets from the downloadable version and found that there is an extra block of javascript. Not sure how it's getting appended in calcite-web.js. Here is how it looks like:

```
/* living-atlas-next - v1.0.0-beta.24 - 2016-07-11
*  https://github.com/ArcGIS/living-atlas-next
*  Copyright (c) 2016 Environmental Systems Research Institute, Inc.
*  Apache 2.0 License */
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (factory());
}(this, function () { 'use strict';

  /* calcite-web - v1.0.0-beta.24 - 2016-06-01
  *  https://github.com/esri/calcite-web
  *  Copyright (c) 2016 Environmental Systems Research Institute, Inc.
  *  Apache 2.0 License */
  (function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    (global.calcite = factory());
  }(undefined, function () { 'use strict';

    // ┌────────────────────┐
    // │ Class Manipulation │
    // └────────────────────┘

```

Not sure, whether something from my Gruntfile is causing this issue. If you want I can send you the gruntfile we are using , if that will help us to narrow down the issue.

**Comment by nikolaswise** [comment]
Yes please! E-mail or private gist or link to the repo or whatever would work for you.

**Comment by nikolaswise** [comment]
Tooling trubs!
