### ISSUE TITLE
Add new languages to type sample page

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#613]
Need to test the following languages on http://esri.github.io/calcite-web/page-layouts/type-comparison/

Hindi 
Slovak 
Bosnian

**Comment by jona7150** [comment]
Looks like we will add Hindi, Bosnian, and Slovak. Just need to add them to site and verify.

**Comment by paulcpederson** [comment]
addressed, will be part of next push

**Comment by paulcpederson** [comment]
fyi this page has moved to http://esri.github.io/calcite-web/examples/i18n/
