### ISSUE TITLE
Numbers in numbered list off in IE 11

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#614]
Noticed this in the usability testing videos done at UC. I think this is IE 11 but it might be 10.

![screen_shot_2016-07-11_at_1_40_47_pm](https://cloud.githubusercontent.com/assets/378557/16746002/3af8effe-476d-11e6-962f-6417a8a6be55.png)

**Comment by nikolaswise** [comment]
@patrickarlt I've looked at this, and have *no* idea how this is being caused. Will try to fix, but might be backburner.

**Comment by paulcpederson** [comment]
fixed in pr
