### ISSUE TITLE
Dots to Checkmarks on Pricing Table

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-web#615]
On Calcite Web Pricing Table:

Let's change the icon font class from icon-ui-radio-checked

to

icon-ui-check-mark

**Comment by paulcpederson** [comment]
addressed on the `restructure` branch, will be fixed once that is merged/released

**Comment by paulcpederson** [comment]
updated, example moved to http://esri.github.io/calcite-web/examples/e-commerce/
