### ISSUE TITLE
tables - add modifier class to remove border lines

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#619]
Proposing to have an additional class to remove vertical borders and/or all border lines. This modifier class should work in conjunction with the striped modifier class, so a table can have striped alternating rows, but remove the lines.

@nikolaswise @paulcpederson @bstifle @asangma @HeathMeyette

**Comment by nikolaswise** [comment]
@fgarofalo10 `.table-striped` and `.table-plain` on the same table will do this already.
