### ISSUE TITLE
Add pattern for creating icons inside a circle

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#622]
Right now lots of sites are using an "Icon inside a circle pattern" for various things:

![screen shot 2016-07-18 at 10 53 50 am](https://cloud.githubusercontent.com/assets/378557/16924814/ebf0d0ca-4cd5-11e6-83fd-05871136612a.png)
![screen shot 2016-07-18 at 10 52 40 am](https://cloud.githubusercontent.com/assets/378557/16924782/c704f688-4cd5-11e6-9428-48a9ab48a38e.png)
![screen shot 2016-07-18 at 10 52 57 am](https://cloud.githubusercontent.com/assets/378557/16924785/cc1e236a-4cd5-11e6-8002-30769e28367c.png)

It would be nice to be able to standardize this as a pattern and use any Calcite Web icon so teams wont always have to create tons a new graphics when laying out pages. This might also help resolve https://github.com/ArcGIS/arcgis-for-developers/issues/3041 faster.

**Comment by patrickarlt** [comment]
Would also be nice to be able to use this pattern next to a header.

**Comment by nikolaswise** [comment]
Going to avoid this for now, since its easy enough to make a round div in normal css, and a round div is a round div. I think this should be largely handled in the asset creation part of a project, so we can have those nice drop shadow icons in circles with gradients.
