### ISSUE TITLE
Filterable Side Nav/Accordion pattern

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#623]
Like the JS API's API Reference but just display the links that match the search in the sidebar instead of somewhere else in the page.

![screen shot 2016-07-18 at 12 28 54 pm](https://cloud.githubusercontent.com/assets/378557/16927645/3da2e98c-4ce3-11e6-9ae5-6614b5ecb64f.png)

**Comment by nikolaswise** [comment]
I like this, and should be an easy combination between existing patterns.

**Comment by nikolaswise** [comment]
Not going to do this pattern for v1. Maybe a future feature.
