### ISSUE TITLE
Idea: Calcite Theme for Wordpress

### ISSUE THREAD

**Issue by hhkaos** [Esri/calcite-web#633]
It would be great to create a Theme for Wordpress using Calcite ... hehe, but I guess this is not an easy task ^_^

**Comment by nikolaswise** [comment]
@hhkaos Actually, this is on the agenda for the next month or so. Will keep you posted. Will be another repo probably tho.

**Comment by calvinkwon** [comment]
@nikolaswise is there any update on this? : )

**Comment by nikolaswise** [comment]
This is no longer my department @calvinkwom - the project is open to PRs tho!

**Comment by calvinkwon** [comment]
@nikolaswise I apologize.. I am not familiar with the jargon. Could you explain what you mean by "PR?"
So is it possible to use the framework for wordpress?

**Comment by hhkaos** [comment]
Sorry @calvinkwon , PR means "Pull Requests"
