### ISSUE TITLE
Block group display issues with odd numbered items

### ISSUE THREAD

**Issue by jhough10** [Esri/calcite-web#636]
Flex grow is causing an issue with rows that have less than the set amount of blocks. 

Essentially, when you use `.block-group-4-up` and say the last row has only 1 block in it, then that last block will span the full width of the entire block group.

When you set `flex-grow: 1` to `flex-grow: 0` the issue resolves itself.

**Comment by nikolaswise** [comment]
Addressed in `v1.0.0-beta.29`
