### ISSUE TITLE
Input modifiers are broken

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#645]
`input-error` and `input-warning` appear to be broken. 

The `form-hint` classes also appear unstyled. We should either remove these from the documentation, or update these classes and take care of form validation for real. 

Related to #602

**Comment by paulcpederson** [comment]
Also, as a rule we should think about moving to marking optional fields rather than required fields. [[1]](http://www.formulate.com.au/blog/required-versus-optional-fields-new-standard) [[2]](http://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/) [[3]](http://www.lukew.com/ff/entry.asp?725)

**Comment by nikolaswise** [comment]
Yeah, this should be a pretty aggressive movement on forms in general I think. We might have to do some js for proper validation, if we want floating placeholder-to-label, etc etc.

**Comment by nikolaswise** [comment]
removed doc in #650, opened a new issue for form validation in #651
