### ISSUE TITLE
.btn-clear buttons not WCAG compliant with table-striped

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#649]
![2016-08-10_16-26-20](https://cloud.githubusercontent.com/assets/3503751/17574568/374cc2a6-5f17-11e6-836b-0a771a244c09.png)

.btn-clear buttons used within a table with .table-striped are not compliant. The button text color is #0079c1 , button background is #f8f8f8 , contrast ratio is 4.39. Slightly lower than 4.5 (thanks @TaoZhang )

Please create a .btn-clear button with a #fff fill for the default state, and a #005e95 fill for the hover / focus state, such as:
![2016-08-10_16-25-08](https://cloud.githubusercontent.com/assets/3503751/17574625/b76ec74a-5f17-11e6-84a6-958706bf52a5.png)
.btn-clear2{color:#0079c1;background:#fff;border-color:#0079c1}
.btn-clear2:hover{color: white; background: #005e95; border-color: #005e95; }

@nikolaswise @paulcpederson @asangma @HeathMeyette @snelsonux @wcoleman0000

**Comment by nikolaswise** [comment]
Good call on this one @fgarofalo10 addressed in #650
