### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by nikolaswise** [Esri/calcite-web#651]
Needs to be excellent and also very good!

**Comment by paulcpederson** [comment]
My thoughts on this are:

1. provide a js hook that adds a class to the input once the input has had some content in it (ie. the user has begun filling it out
2. use `valid` and `invalid` from CSS once this class has been added (so when the user starts filling it out they get feedback on if they've done it correctly). These styles should be more subtle than a red outline with red text.
3. Provide styles for input errors. When the user has filled out the form and they messed it up, or skipped a required field, we should have a way to communicate error messages next to the form fields that were incorrect

So essentially as a developer, I get the initial inline help and validation for free via `calcite-web.js` and then I handle post-submit error messages myself with documented classes. 

I also think we should move to using `optional` to denote optional fields.

Does all that make sense? /cc @asangma

**Comment by nikolaswise** [comment]
@paulcpederson That makes sense to me, and I endorse those things. Interested in @asangma's thoughts also

**Comment by nikolaswise** [comment]
Addressed in #697 to a certain extent, could use more HTML5 psuedo selectors and adjacents, but for now assuming that form validation is happening explicitly in the client.

**Comment by fgarofalo10** [comment]
@nikolaswise @paulcpederson - are the new designs/styles, documented on esri.github.io/calcite-web/documentation ?

cc @tdolanwork

**Comment by paulcpederson** [comment]
@fgarofalo10 no, #697 hasn't been merged yet

**Comment by patrickarlt** [comment]
@paulcpederson do you still think we should try to handle form validation via `calcite-web.js`? Given that so many teams use frameworks that have really advanced validation capabilities should we just provide the styling?

**Comment by paulcpederson** [comment]
@patrickarlt I am now thinking that handling the styling would honestly be enough. This is a lot like alerts. Alerts are just pieces of HTML and CSS that developers can turn on and off as they need to.

I Nik's pr gets us close but I might tweak the styles before we release.
