### ISSUE TITLE
label-yellow doesn't pass WCAG AA color contrast

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#654]
![2016-08-16_16-49-43](https://cloud.githubusercontent.com/assets/3503751/17719722/86c12354-63d1-11e6-8326-35ce9f35e788.png)

Using the text color of `#595959` with the same background yellow color, does pass AA rating.
![2016-08-16_16-50-44](https://cloud.githubusercontent.com/assets/3503751/17719743/a9493da8-63d1-11e6-89ab-1c0416850a88.png)

@paulcpederson @nikolaswise @alansangma @snelsonux

**Comment by fgarofalo10** [comment]
@nikolaswise @paulcpederson @bstifle

**Comment by paulcpederson** [comment]
addressed in #661 , will be part of next release
