### ISSUE TITLE
links with the table-striped gray background row color don't pass WCAG

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#655]
related to https://github.com/Esri/calcite-web/issues/649

Perhaps the actual issue is the gray background for
`.table-striped tr:nth-child(even) td {
    background-color: #f8f8f8;
}`

WCAG passes AA for blue text of #0079c1 if the background color is **#fcfcfc**
`.table-striped tr:nth-child(even) td {
    background-color: #fcfcfc;
}`

@nikolaswise @paulcpederson @alansangma

**Comment by paulcpederson** [comment]
@fgarofalo10 there is no brand gray in between white and off white: https://github.com/Esri/calcite-colors/blob/master/scss/variables.scss#L95

That said, we mix `$white` and `$off-white` to get `#fcfcfc` for the hover state of tabs, so we've used this color before. I wonder if we should add this color to the palette (maybe as `$Calcite_Gray_075`?)

Doing this makes the stripe *very subtle*:

![screen shot 2016-08-17 at 11 04 00 am](https://cloud.githubusercontent.com/assets/1031758/17747606/6619b8f2-646a-11e6-938e-aba945d15448.png)

Not sure if that is too subtle? Another option would be making links inside a striped table darker blue. The easiest way to do that would be to add a `link-dark-blue` modifier class.

**Comment by fgarofalo10** [comment]
@kyle-03674 @bstifle thoughts on the additional color, added to the palette?

**Comment by kyle-03674** [comment]
I'm not sure the lighter gray background helps here. I like the solution in #649 where the button fill became white, but the row fill was the same. The row fill, as @paulcpederson says, is _very subtle,_ so subtle than many displays would blow out that detail and just look "white." In fact, on many displays, `$Calcite_Gray_100` might not even show.

Is there a problem to leaving tables as they are? Maybe I missed something

**Comment by fgarofalo10** [comment]
@kyle-03674 the accessibility compliance issue also occurs with a blue link `<a href="#">` (#0079c1) against the current gray of a striped table row `.table-striped tr:nth-child(even) td { background-color: #fcfcfc; }`

**Comment by paulcpederson** [comment]
ok, I've elected to just make the links `$dark-blue` which passes AA #661

**Comment by kyle-03674** [comment]
ok

**Comment by paulcpederson** [comment]
will be part of next release
