### ISSUE TITLE
aria helper is expecting arrays to contain non null element. Lead to crash

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-web#656]
For example, when the `hide` (https://github.com/Esri/calcite-web/blob/master/lib/js/helpers/aria.js#L19) is called with an array containing null values, the function will crash.
Arrays containing null values could be passed the aria functions in such scenario:
https://github.com/Esri/calcite-web/blob/master/lib/js/patterns/modal.js#L38
If the document does not contain a `.wrapper` element or a `.footer` element, `document.querySelector` will return a null value.

I think there are two ways to fix this issue:
- make aria functions more robust
- and/or prevent calling aria functions with null values in arrays.

I have forked the repository and I will submit a PR.

Please advise.

**Comment by paulcpederson** [comment]
thanks for the pr, @ffaubry I think this issue is resolved now.
