### ISSUE TITLE
Calcite issues with card CSS in IE 10 and 11

### ISSUE THREAD

**Issue by tdolanwork** [Esri/calcite-web#662]
IE 10 and 11 are not rendering this page in the same way as Chrome and Firefox. It seems to be an issue with IE not interpreting how the height of the cards is dynamically calculated.

http://clidev.esri.com/team/FrankG/myesri/training.html
![ie11_issue_chrome_myesri](https://cloud.githubusercontent.com/assets/21069320/17904323/c3efc21a-6923-11e6-8beb-35741ec1682e.PNG)

![ie11_issue_ie_myesri](https://cloud.githubusercontent.com/assets/21069320/17904322/c3eca0da-6923-11e6-9b55-6f74623b3fb8.PNG)

[IE 10 and 11 Calcite issues.docx](https://github.com/Esri/calcite-web/files/433235/IE.10.and.11.Calcite.issues.docx)

**Comment by fgarofalo10** [comment]
@nikolaswise @paulcpederson @bstifle

**Comment by paulcpederson** [comment]
@tdolanwork thanks for finding this. I'll try to fix this in the coming week.

**Comment by paulcpederson** [comment]
Ok, this will be fixed in the next release.

**Comment by paulcpederson** [comment]
addressed in #661
