### ISSUE TITLE
Cannot use Calcite on the same page as the ArcGIS JS API

### ISSUE THREAD

**Issue by sympletech** [Esri/calcite-web#663]
When including calcite on a page that has the new 4.0 JS API the map surface renders no map

**Comment by paulcpederson** [comment]
@sympletech This issue is actually covered in https://github.com/Esri/calcite-web/issues/580

The problem will be solved on the JSAPI side in the September release.

Until then, you can add the following CSS that fixes it in your own project:

```
   .esri-bitmap {
      max-width: none;
      transform-origin: top left;
    }
```
