### ISSUE TITLE
Combine with JS API

### ISSUE THREAD

**Issue by hhkaos** [Esri/calcite-web#664]
I'm trying to show how to create a [custom backoffice with ArcGIS Online webmap editor embeded](https://jsbin.com/fimase/2/edit?html,output) and then I want to show how to create a custom panel where the developer can "extend" that editor, for example: adding sources from it's own database.

Then, [I'm trying to use our JS API at the same time to load a webmap inside that panel](https://jsbin.com/nitacoqeso/1/edit?html,output) but it doesn't work, is it possible?

Thanks in advance!

**Comment by paulcpederson** [comment]
@hhkaos  This issue is actually covered in https://github.com/Esri/calcite-web/issues/580

The problem will be solved on the JSAPI side in the September release.

Until then, you can add the following CSS that fixes it in your own project:

```
   .esri-bitmap {
      max-width: none;
      transform-origin: top left;
    }
```

**Comment by hhkaos** [comment]
Great Paul, thx!!!
