### ISSUE TITLE
search result links broken

### ISSUE THREAD

**Issue by bsvensson** [Esri/calcite-web#665]
When I go to http://esri.github.io/calcite-web/ and search for "panel", it takes me to http://esri.github.io/calcite-web/search/?q=panel.  If I click on any of the links, it takes me to a 404 page, e.g. http://esri.github.io/calcite-web/components/#panels

I think it should go to things like http://esri.github.io/calcite-web/documentation/components/#panels - note the `/documentation` folder.

**Comment by paulcpederson** [comment]
thanks, @bsvensson

**Comment by bsvensson** [comment]
np @paulcpederson - impressive 4-minute turnaround for fixing  :)
