### ISSUE TITLE
Couple of bugs

### ISSUE THREAD

**Issue by hhkaos** [Esri/calcite-web#669]
I have seen one thing broken: [Marketing samples](http://esri.github.io/calcite-web/examples/marketing/).

And also when clicking any "View HTML" button it add some extra characters at the end of the textarea like `">`, sometimes `</header> ">` (without an opening tag `<header>`), etc.

Cheers!

**Comment by nikolaswise** [comment]
thanks @hhkaos  - this is fixed in #672 and deployed. Turns out I was doing those sample blocks very, very wrong.

**Comment by hhkaos** [comment]
hahaha, great, but it is not fixed in the gh-pages branch, right?

**Comment by hhkaos** [comment]
I mean, the carousel and the image switcher:
![screenshot 2016-09-13 18 24 37](https://cloud.githubusercontent.com/assets/826965/18482169/633b3ffe-79df-11e6-82d3-9c861709f0b6.png)

**Comment by nikolaswise** [comment]
Oh! Those aren't broken per se – rather they just don't really work yet. Another team is bringing those to completion before we move them in for real.

**Comment by hhkaos** [comment]
hahah, okok 👍 , thx
