### ISSUE TITLE
Firefox bug: Long non-breaking text collapsing block groups.

### ISSUE THREAD

**Issue by nullrocks** [Esri/calcite-web#671]
When there is non-breaking text inside a `.block` and the block is too small, instead of overflowing the `div.block` or breaking the text to new lines it makes the block jump below.

### Example

![screen shot 2016-09-09 at 12 09 29 pm](https://cloud.githubusercontent.com/assets/1198518/18395918/7d925ab0-7686-11e6-973b-95bb6a9565fa.png)
_Second row, third column: "ArcSDE/Enterprise Geodatabase" is pushing the next .block below_

### Solution?
```css
word-break: break-all;
```
or
```css
min-width: 0;
```

**Comment by nikolaswise** [comment]
I like the `min-width: 0` line - any preference on this @paulcpederson ?

**Comment by paulcpederson** [comment]
definitely not `word-break: break-all`. I agree `min-width: 0` is probably the way to go.

**Comment by nikolaswise** [comment]
Addressed in #672
