### ISSUE TITLE
rtl - padding for .side-nav-link doesn't flip

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#673]
LTR padding for .side-nav-link:
padding: 0.51667rem 1.55rem 0.51667rem 0.51667rem;

@nikolaswise @paulcpederson @tdolanwork

**Comment by nikolaswise** [comment]
@fgarofalo10 side nav links don't have asymmetrical padding. 

https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/patterns/_side-nav.scss#L29
