### ISSUE TITLE
Input error doesn't work

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#677]
adding `input-error` class to inputs doesn't actually override the border color of the input and it looks no different.

Should fix this in conjunction with form validation styles ( #651 )

**Comment by paulcpederson** [comment]
![screen shot 2016-09-23 at 10 14 29 am](https://cloud.githubusercontent.com/assets/1031758/18794872/9297f85c-8176-11e6-96b2-131dd7088867.png)

**Comment by nikolaswise** [comment]
Addressed in #697 — now uses `.input-helper-error`
