### ISSUE TITLE
Button with Icons - not clickable 

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#682]
When displaying an icon within a button, such as:

`<a href="#" class="btn btn-small btn-clear js-modal-toggle" data-modal="recipient_edit" title="Edit"><span class="icon-ui-edit padding-left-0 padding-right-0"></span></a>`

-or-

`<button class="btn btn-small btn-clear2 js-modal-toggle" data-modal="recipient_edit" title="Edit"><span class="icon-ui-edit padding-left-0 padding-right-0"></span></button>`

Screen capture of implementation example:
![2016-10-05_iconbuttons](https://cloud.githubusercontent.com/assets/3503751/19128532/9a658a14-8af8-11e6-9c77-114b392e5907.png)

the <span> containing the icon is a non-clickable area of the button

@nikolaswise  @paulcpederson  @tdolanwork

**Comment by paulcpederson** [comment]
@fgarofalo10 is there a reason you have to use a `<span>`? Why not just put the icon on the button?

```
<button class="btn btn-small btn-clear icon-ui-edit icon-ui-flush js-modal-toggle" data-modal="recipient_edit" title="Edit"></button>
```

That seems to work fine.

**Comment by fgarofalo10** [comment]
ah, I didn't know `icon-ui-flush` was an option, it doesn't seem to be documented on the Icons page: http://esri.github.io/calcite-web/documentation/icons/

I'll give that a try

**Comment by paulcpederson** [comment]
@fgarofalo10 good point, I'll update the docs!

**Comment by paulcpederson** [comment]
opened #684 to remember, closing this issue.
