### ISSUE TITLE
Remove Expanding Navigation JavaScript

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#687]
> This was removed in version beta.24 [...] however I have noticed that the JS still exists in the repo.

https://github.com/Esri/calcite-web/blob/master/lib/js/patterns/expander.js

**Comment by lheberlie** [comment]
I also noticed that the search header in the developers site, as well as the JavaScript API landing page search both use the `js-expand-toggle` that is in the `expander.js`, correct?

```
<developers-search class="right" placeholder="map, feature layer, rest api, geocoding, ect...">
      <div class="margin-left-1 js-expand-toggle top-nav-list" data-expand="search">
        <a href="#" class="icon-ui-search top-nav-link">Search</a>
      </div>
    </developers-search>
```

```
<section class="expand js-expand panel panel-no-padding is-active" data-expand="search">
        <div class="grid-container padding-trailer-half padding-leader-1 padding-trailer-1">
          <form method="GET" action="/search/" class="column-24">
            <label>Search ArcGIS for Developers

              <a href="#" class="icon-ui-close js-expand-toggle right" data-expand="search"></a>
              <div class="input-group">
                <input class="input-group-input" type="search" name="q" placeholder="map, feature layer, rest api, geocoding, ect...">
                
                
                <span class="input-group-button">
                  <button type="submit" class="btn btn-clear icon-ui-search">Search</button>
                </span>
              </div>
            </label>
          </form>
        </div>
      </section>
```

cc: @patrickarlt, @jf990

**Comment by patrickarlt** [comment]
@lheberlie The CSS for this was removed several versions ago and @nikolaswise ported it into the developers site as a part of the `<developers-search>` component so we don't use this JS at all. For out next release we are changing to the new search pattern anyway so we wont use expanders at all.

**Comment by nikolaswise** [comment]
@lheberlie reference current Calcite Web documentation search for preview of new search UI

**Comment by lheberlie** [comment]
So ... it sounds like I need to move https://github.com/Esri/calcite-web/blob/master/lib/js/patterns/expander.js into the ArcGIS API for JavaScript SDK repo, as it sounds like it is on the way out? We use it in our modules overview page: https://jscore.esri.com/javascript/latest/api-reference/index.html#modules-in-esri

**Comment by nikolaswise** [comment]
This JS has been removed in #697
