### ISSUE TITLE
Few more icons

### ISSUE THREAD

**Issue by alaframboise** [Esri/calcite-web#699]
Any chance of getting a few more icons built in? Very helpful for building map apps.

- About
- Info
- Slides/Bookmarks
- Legend

Thanks!

**Comment by paulcpederson** [comment]
@alaframboise we can ask the icon team to do more and add them. I should ask that we do have in info icon `icon-ui-description`

**Comment by oknoway** [comment]
We could use icons for:

- Ideas (lightbulb?)
- Video
- Training/Presentation

**Comment by alaframboise** [comment]
Based on some apps I created lately, here's a few more:

* 2D
* 3D
* LayerList

**Comment by paulcpederson** [comment]
Closing this as Calcite Web is going to move away from the icon font, integrating the svg icons from the icon team directly from their repository: http://clidev.esri.com/calcite/arcgis-apps-icons/
