### ISSUE TITLE
Layouts with pre/post that add up to 24 break on Firefox and Safari

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#701]
We encourntered a bug in Safari and Firefox affecting some of our layouts on the Developers site. This occurred when we had a combination of columns and pre/post that added up to 24, like so:

```html
<div class="grid-container">
  <div class="column-6">
    6 Columns
  </div>

  <div class="column-17 pre-1">
    17 Columns, Pre 1
  </div>
</div>
```

At 1509-1522 pixels wide this layout breaks. Inspecting the elements it looks like this is what is happening:

```
8.5 + 345.5 + 8.5 + 60.867 + 8.5 + 1010.08 + 8.5 = 1450.447
```

This ends up equaling about half a pixel more then we have width for so the 17 column wide element wraps around.

This leaves me wondering what the actual value of pre/post is. Since the layout above could be easily solved by doing this:

```html
<div class="grid-container">
  <div class="column-6">
    6 Columns, Floated Left
  </div>

  <div class="column-17 right">
    17 Columns, Floated Right
  </div>
</div>
```

But I bet for other cases we will really need pre/post so we could do some more testing on this.

**Comment by patrickarlt** [comment]
@paulcpederson Upon further debugging of some issues it appears that adding `first-column` to the `column-6` also fixes this. Apparently this was part of [Beta 25](https://github.com/Esri/calcite-web/blob/master/CHANGELOG.md#100-beta25), but the doc is really vague on where it is necessary to use `first-column`

> The `first` and `last` classes are used for aligning grid columns when the Grid System is unable to determine which columns are first or last in their rows. 
> 
> http://esri.github.io/calcite-web/documentation/grid/#first-and-last

In my above example it seems really easy to determine what the first and last column. Is there something I'm missing here?

**Comment by paulcpederson** [comment]
@patrickarlt your layout above should work without the `first-column` class. `first-column` is only necessary in situations where we can't select it for some reason.

Pre and post are necessary in some cases to do 3+ column layouts. IE. multiple columns with space in between them

This is a bug related to a rounding error most likely. I was unable to reproduce in firefox until I turned on permanent scroll bars. I'll look into it and try to fix the column math/rounding.

**Comment by patrickarlt** [comment]
> first-column is only necessary in situations where we can't select it for some reason.

I don't think this is entirely true anymore. [In Beta 25](https://github.com/Esri/calcite-web/blob/master/CHANGELOG.md#100-beta25) it looks like Nik removed an automatic check for this:

> naive check for `column pre-n:first-child` use explicit `.first-column`

Looks like any kind of automated check was removed in https://github.com/Esri/calcite-web/commit/29020f922b6711cf6f528b9a1b334c1e01f492ec.

**Comment by paulcpederson** [comment]
@patrickarlt it still detects first columns for you if you haven't use `pre-` though. In your example above you used:

```
<div class="grid-container">
  <div class="column-6">
    6 Columns, Floated Left
  </div>

  <div class="column-17 right">
    17 Columns, Floated Right
  </div>
</div>
```

That doesn't need a `first-column` class, there is no `pre-`.  It's due to a rounding error in the math for column width. I'll fix as part of next release.
