### ISSUE TITLE
Style disabled form elements

### ISSUE THREAD

**Issue by nullrocks** [Esri/calcite-web#704]
### Missing style/indicator for disabled elements.

```html
<input type="text" disabled>
<!-- You can't tell the difference -->
<input type="text">
```

### Suggestions
- Lower the opacity a little bit for disabled elements
```sass
input, select, textarea {
  &[disabled]{
    opacity: 0.7;
  }
}
```
- Disabled indicator: text, color, border?.

**Comment by paulcpederson** [comment]
@nullrocks a commit that does this was merged but it has't been released yet (https://github.com/Esri/calcite-web/issues/675), but I wanted to tweak that style for the release anyways. I agree that lowered opacity is the way to do this. I'll be sure to put this in the next release.
