### ISSUE TITLE
Improvement add classes for SVG icons

### ISSUE THREAD

**Issue by bradleywertman** [Esri/calcite-web#714]
With the switch to SVG icons, please add the classes back instead of requiring to copy out the entire svg code. 

Without the icon classes, html structure would have constant edits for any icon updates, not to mention the headache when trying to port from the previous frameworks.

...unless this feature is not documented yet.

**Comment by paulcpederson** [comment]
@bradleywertman I think I'm leaning towards making both the icon font and svg icons available. I'm trying to add them into the next release.
