### ISSUE TITLE
Provide non-link options for .top-nav-title

### ISSUE THREAD

**Issue by ssylvia** [Esri/calcite-web#729]
No matter what element is used, there is still the hover styling that makes it look like a link.

Maybe only include the [hover styling](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/patterns/_top-nav.scss#L38) if the tag is an anchor tag.

**Comment by paulcpederson** [comment]
@ssylvia I like this idea. Looks like some folks actually override this altogether even if the title is still a link (http://opendata.arcgis.com/). Further, the newer designs for the global nav by @asangma and crew remove the hover style blue underline/active state all together and move towards a plain old link hover color of blue for just the text, no bar. 

I'll put this in the next release. :+1:

**Comment by asangma** [comment]
Yo! 
> remove the hover style blue underline/active state all together and move towards a plain old link hover color of blue for just the text, no bar.

To be clear, we are suggesting this for **branded** elements...or text that would be like that, e.g. "ArcGIS for Developers".

We retain the bottom bar on other nav items for accessibility reasons, i.e. a color and shape change.

**Comment by paulcpederson** [comment]
@asangma perfect, that's very much what we're thinking about here.

**Comment by ssylvia** [comment]
Awesome, thanks everyone. Yep, we're planning to use this for logged-in user navbar that sits on top of our story map builders. The "branded" title is just the app name and there's no navigation outside the single page app:

![image](https://cloud.githubusercontent.com/assets/1211360/21140400/d32d6c52-c105-11e6-9f35-4e490a893c38.png)
