### ISSUE TITLE
Update the grid with a more lightweight alternative

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#730]
Currently the grid takes up about 60% of the final weight of the framework. It is the hardest Sass code to develop and maintain because it is so complex, and the generated CSS is far too specific and verbose. 

Investigate other systems for CSS grids that can help reduce the weight of calcite web. A new grid could be developed and then old grid could be deprecated or moved behind a flag.

There are a couple ideas for how we could implement this, one is to use flex box (like http://flexboxgrid.com/). The other is to wait until the [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/) spec gains [higher support](http://caniuse.com/#feat=css-grid) and polyfill for older browsers.

**Comment by patrickarlt** [comment]
I wouldn't hold my breath for CSS Grid support at the level we need it. A flexbox grid would be really nice though.

**Comment by paulcpederson** [comment]
Going to close this issue and I can open a new issue in the future if we really want to address this.

**Comment by paulcpederson** [comment]
https://robots.thoughtbot.com/building-the-future-of-floated-css-grids#the-push-left-grid
