### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-web#733]
Is there a dark theme?

**Comment by asangma** [comment]
cc @paulcpederson

**Comment by paulcpederson** [comment]
@asangma no. We haven't had folks clamoring for that yet. It's been discussed, and I'm all for it. 

Implementation wise, I think we could perhaps engineer a way for Sass to do most of the work on this for us by overriding color variables. So you'd create a new Sass file `calcite-web-dark.scss`. All it would be is variable overrides and an import of calcite-web:

```
$white:                       rgba(0, 0, 0, 1);
$off-white:                   $Calcite_Gray_700;
$lightest-gray:               $Calcite_Gray_650;
$lighter-gray:                $Calcite_Gray_600;
$light-gray:                  $Calcite_Gray_550;
$gray:                        $Calcite_Gray_500;
$dark-gray:                   $Calcite_Gray_450;
$darker-gray:                 $Calcite_Gray_400;
$darkest-gray:                $Calcite_Gray_350;
$off-black:                   $Calcite_Gray_200;
$black:                       $Calcite_Gray_100;

@import "calcite-web";
```

There may be other work that would go into a dark theme, but I think that altering color variables would get you most of the way there.

**Comment by asangma** [comment]
Right on.

What do you think about [this guy](https://github.com/Esri/calcite-colors/blob/master/scss/variables_dark.scss)?

> We haven't had folks clamoring for that yet.

Roger that.  Seems like it'd be a good offering...also the 4.x API has its built in themes, and we could get some alignment there too.

**Comment by paulcpederson** [comment]
![screen shot 2016-12-20 at 1 53 59 pm](https://cloud.githubusercontent.com/assets/1031758/21369456/de1e87c0-c6bb-11e6-9180-2a134f54ea6a.png)

In progress, looking good.

**Comment by paulcpederson** [comment]
will be part of the next release
