### ISSUE TITLE
exports of JS methods as individual methods for smaller production builds

### ISSUE THREAD

**Issue by ssylvia** [Esri/calcite-web#736]
When using a single JS method, I am required to download the entire calcite JS file.

Currently I have the following options: 

```js
import calcite from 'calcite-web';

// Downloads the whole file
// Can use as
calcite.module();
```

or 

```js
import {drawer} from 'calcite-web';
// still downloads the whole file
//can use as
drawer();
```

Ideally we should allow

```js
import drawer from 'calcite-web/drawer';
// only includes "drawer" module
//can use as
drawer();
```

or

```js
import {drawer} from 'calcite-web';
// only includes "drawer" module with tree-shaking in production builds
//can use as
drawer();
```

**Comment by paulcpederson** [comment]
@ssylvia we use es6 modules internally, but only distribute the bundled js file. I think we could do this pretty easily.

**Comment by paulcpederson** [comment]
@ssylvia so, I'm looking into this right now, and I noticed that we already copy the source js over to the `dist` on release. For example, you can actually do this already:

```
import drawer from 'calcite-web/dist/js/patterns/drawers';
drawer();
```

The filepath is kind of gross, though, and doing it that way would mean that if I changed how the folder is organized in the future it would be a breaking change, which isn't ideal.

I'm actually leaning towards creating a file at the root of the project with named exports so you could use it like:

```
import {drawer} from 'calcite-web/es6';
```

I think I could also make the the `jsnext:main` and `module` fields in `package.json` point to the named exports file. I think both Rollup and Webpack 2 support this field so when you do

```
import * as calcite from 'calcite-web'
```

Rollup and Webpack 2 will prioritize the file pointed to from `module` automatically.

Does that make sense/will that fit your particular use case?
