### ISSUE TITLE
Lighten placeholder text color

### ISSUE THREAD

**Issue by isaacviel** [Esri/calcite-web#744]
From @jgravois in the ArcGIS for Developers GitHub. 

During a recent hackerlab in Austin, Texas, attended primarily by folks without much programming experience, I logged quite a few bits of nitpicky feedback.  Some issues were exacerbated by the fact that the majority were using IE11 to access the site.  Others were generic to all browsers.

- [x] **Usability**

In Edge/IE, Placeholder text color is **not** distinguishable from actual entered text.

**Steps to reproduce:**

1. Layers > Create New Layer
2. Enter a new layer `title` or `tags`. the entered text is the same color was the placeholder.

**Expected behavior:**

I watched a user try to create a layer called 'My Cool Layer', fail, and have no idea which element was problematic.

**Browser and version:**

Edge/IE11

**URLs affected:**

https://developers.arcgis.com/layers/#/new/

**Environment affected (Dev, QA, Prod):** 
Production

**Screenshot:**

![screenshot 2016-12-16 08 56 45](https://cloud.githubusercontent.com/assets/3011734/21271842/75eaa7d0-c371-11e6-9168-723ca669e917.png)

**Comment by macandcheese** [comment]
@isaacviel, can you verify that you are still encountering this on your end? I've looked in IE / Edge and the Placeholder text is slightly lighter than the inputted text. 

I think the thin font weight exacerbates it. I'd be hesitant to make the placeholder text any lighter, but some options to improve are: moving from $off-black to $black for inputted text, or bumping the font-weight of input fields to 500 / 'avenir-demi'. Thoughts?
