### ISSUE TITLE
Certain grid layouts break above the largest break point

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#745]
This is most likely related to the work done to fix pre and post in arabic for v1.0.0-rc.1
![screen shot 2016-12-20 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/1031758/21370892/f63ca9d4-c6c2-11e6-9359-61f1bd3beffb.png)

**Comment by macandcheese** [comment]
I think this may still be happening, see: http://esri.github.io/calcite-web/examples/core/
The "view html" area content is centered on some screens, left aligned on very large screens. @paulcpederson Is this a case of not having the correct classes assigned?
