### ISSUE TITLE
Update user dropdown menu with newer designs

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#749]
Moving towards a slightly different lockup for the user dropdown/apps dropdown. The documented pattern should be updated to look more like the newer designs.

<img width="583" alt="screen shot 2016-12-21 at 8 30 01 am" src="https://cloud.githubusercontent.com/assets/1031758/21397247/e607cc3e-c757-11e6-8810-e64ef33cb828.png">

Hover/Focus states:

<img width="485" alt="screen shot 2016-12-21 at 8 30 22 am" src="https://cloud.githubusercontent.com/assets/1031758/21397248/e610ad22-c757-11e6-8b1c-ac415dcd4048.png">

**Comment by patrickarlt** [comment]
@paulcpederson is the `MJP@mysandiego` the users email address or username? Also is a shared design for the App Switcher coming anytime soon so we can integrate it on the developer site?

**Comment by paulcpederson** [comment]
@patrickarlt that's the username.

I'll ask around about the App Switcher

**Comment by asangma** [comment]
Small note: looks like the down caret is no longer needed on the user.

**Comment by patrickarlt** [comment]
@asangma if the user is a dropdown don't we need the caret?

**Comment by asangma** [comment]
@patrickarlt Yeah...that is possible.

The conversation currently is going something like this:

**Dude 1:** The user is a dropdown, so it should get a caret.
**Dude 2:** Wait...isn't the app switcher also a dropdown, and wouldn't that rule mean it gets a caret too.
**Dude 1:** That would be weird.
**Alan:** Yeah...no.  A caret on the app switcher icon would be an icon with an icon.  How about this? We consider everything right of the border (i.e. app switcher and user) the truly global part of the global nav.  And as of right now, everything in that section is a dropdown.  Can we nix the caret, and if people start driving off cliffs, we add the caret?
**Dudes 1 and 2:** Alan...you're so smart.

**Comment by patrickarlt** [comment]
@asangma I actually think the caret vastly helps users understand what the item they are about to click is. Consider our new top nav for the developers site:

![ba114522-d1e0-11e6-817c-b5a4cf7c0e6b](https://cloud.githubusercontent.com/assets/378557/21667765/87110d9e-d2b0-11e6-9ac9-8c0e27e34796.png)

The plus icon alone feels really ambiguous.

**Comment by asangma** [comment]
I feel you, bro.
I am also considering exposure to Google products:
![image](https://cloud.githubusercontent.com/assets/12503298/21686995/4cedfa02-d31c-11e6-8f93-b1d42f651784.png)

**Comment by asangma** [comment]
Also, I am sorry for not being more clear.  I am suggesting that the no-caret pattern would be applied to everything right of the border.  So in your screen, it'd apply to your user.  And if there were the app switcher in there, it being right of the border, would also get no caret.

Thoughts?

As a note, this approach came out of an extended discussion with a bunch of apps group designers.

**Comment by asangma** [comment]
@patrickarlt FYI. I'm fully willing to take it back to the web apps designer peeps.  My stance though is that if the account switcher and user controls work without the caret, let's roll without it.

I should also note that I'm mostly thinking about the `esri-global-nav` component.
And with that component, we will want to take the time to test it.  Caret-v-not can be included in those tests.

Annnnd...it looks like the timeline for delivering the `esri-global-nav` component is getting extended due to lack of resources. So yeah...that too.

**Comment by paulcpederson** [comment]
I'm going to close this issue. People that want to use the new global nav user dropdown will be able to install that as a dependency straight from the source. I don't see a reason to have those styles duplicated here.
