### ISSUE TITLE
Responsive block groups not changing for mobile

### ISSUE THREAD

**Issue by ajbroadbent** [Esri/calcite-web#751]
We're having some issues with responsive block groups not updating to phone-block-group-x-up.  When we look at it in Chrome using the device toolbar, it looks fine, but once we open it on an actual mobile device, it doesn't seem that any of the tablet or phone styles are being used.  You can see this on http://doc.arcgis.com/en/arcgis-online/ or on http://docdev.arcgis.com/en/aimeetest/ (where I've been messing around with the HTML a bit to try to get it to work).  On either page, scroll to the Get Started section to see what I'm talking about.  Is there something we're doing wrong, or is this a bug that has been fixed in a more recent version of the code?

**Comment by paulcpederson** [comment]
@ajbroadbent what browser and version? ios safari/mobile chrome/android browser?

I just tried on my phone in both Safari and Chrome on iOS and they both worked fine. But in my iOS Simulator (which uses a dated version of Safari) it displayed like you're talking about. My guess is that you might be using an older version of Safari and it's not playing nice. 

Looks like flex box support in older versions of mobile safari was there but there was no wrapping: 

![screen shot 2016-12-28 at 10 20 18 am](https://cloud.githubusercontent.com/assets/1031758/21528703/49f95f8c-cce9-11e6-9ec4-67042851e139.png)

But the good news is that most people who are using mobile safari are using the latest version as it's updated automatically when you update the OS:

![screen shot 2016-12-28 at 10 34 03 am](https://cloud.githubusercontent.com/assets/1031758/21528720/685751fa-cce9-11e6-8b1b-af55b449c712.png)

**Comment by ajbroadbent** [comment]
That's probably the problem, then.  My phone OS isn't up to date.  Thank you!

**Comment by ajbroadbent** [comment]
It seems like there are still some mobile issues popping up.  This is on an Android:
![image](https://cloud.githubusercontent.com/assets/20780983/21548105/1824e100-cd9f-11e6-8c9b-e6abb402c2be.png)

And this iws on an iPhone 5s with iOS 10.2:
![image](https://cloud.githubusercontent.com/assets/20780983/21548122/31338282-cd9f-11e6-8483-5a3f0e37c661.png)

**Comment by paulcpederson** [comment]
@ajbroadbent I think you are just missing the `viewport` meta tag in the head of those documents:

```
<meta name="viewport" content="width=device-width, user-scalable=no">
```

If I add that to the `head` of the pages that aren't working it seems to work fine.

**Comment by ajbroadbent** [comment]
Perfect! Thank you!
