### ISSUE TITLE
Calcite Color Palette : Make the Authoritative Resource

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#755]
Having discovered discrepancies in how [colors](https://github.com/Esri/calcite-colors/issues/21) and [grids](https://github.com/Esri/calcite-web/issues/754) are displayed in Adobe files versus actual CSS, it should be decided which colors and grids are the true colors and grids, and any files related to the matter should be updated (swatches, photoshop guides, css files).

**Comment by paulcpederson** [comment]
I don't have access to the swatches, photoshop guides, etc, but I would think that the photoshop guide should update to match calcite web as the photoshop file is design collateral and not an actual product. 

I'm going to close this issue, but feel free to reopen with a list of discrepancies that should be fixed on the calcite-web side and I can take a look at updating them.

**Comment by jonathantneal** [comment]
Fair enough. Who do we ping on the design side to be sure they are in conformance?

**Comment by paulcpederson** [comment]
I'm not sure, @asangma do you know the answer to that?

**Comment by asangma** [comment]
Hurm...which Adobe files are you referencing?

Also, I think the approach that the ol' [Patterns site](http://webopsoktaportal.esri.com//Saml?url=http%3A%2F%2Fpatterns.esri.com%2Fcolors%2F) used was a better one because it doesn't depend on a graphics asset.

**Comment by jonathantneal** [comment]
@asangma, that link is not working for me. Would you double check it?

**Comment by asangma** [comment]
☝️ edited.

**Comment by asangma** [comment]
Because this is a closed issue, I will just say that discussion with Bryan indicates that, broadly, web-based reference/tool would be best if there is fluid way to retain a synced ASE<sup>1</sup> file.  And we will get to have a meeting on this...sometime in the future™.

<sup>1</sup>Photoshop & Illustrator palette.

**Comment by paulcpederson** [comment]
Yeah we can reopen if the place those resources live is going to be calcite-web, let me know.

**Comment by asangma** [comment]
> if the place those resources live is going to be calcite-web

Yeah...I was thinking that.

Can we rename the issue to something about **color** if we reopen?

**Comment by asangma** [comment]
#persnickety

**Comment by paulcpederson** [comment]
If you have a dream for the title of this issue, follow that dream, follow your heart.

**Comment by paulcpederson** [comment]
![](http://awesomegifs.com/wp-content/uploads/napoleon-dynamite-dove-hands.gif)

**Comment by asangma** [comment]
LOL!

**Comment by asangma** [comment]
I don't seem to have some permissions on this issue.

**Comment by jonathantneal** [comment]
What permissions are you looking for?

![](http://lghttp.17653.nexcesscdn.net/808B16/cdn_images/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/f/t/ft231a_2.jpg)

**Comment by asangma** [comment]
![dead](https://media.giphy.com/media/eVDL1cV8cjhT2/giphy.gif)

**Comment by asangma** [comment]
edit title, reopen issues, go play with my friends

**Comment by paulcpederson** [comment]
yeah, you're not in the cool club, I could probably add you though if you promise to be cool

**Comment by paulcpederson** [comment]
@asangma ok, you should be able to edit now?

**Comment by asangma** [comment]
![Cool club.](http://media3.giphy.com/media/62PP2yEIAZF6g/giphy.gif)

**Comment by asangma** [comment]
Some suggestions:
- [ ] Web resource is the authoritative one (i.e. not an ASE palette)
- [ ] Retain current Calcite color vars (e.g. `Calcite_Gray_050`)
- [ ] Compatible with Calcite semantic color classes (e.g. `light-blue`, `darkest-gray`)
- [ ] Super easy to see which colors have WCAG AA contrast (e.g. I click on a color and it shows what colors give minimum contrast for 12pt regular text)
- [ ] Easy to keep ASE palette files in sync with web resource

---

**Stuff in order of how often they can change**

| Geological Time | Orbital Time | Social Media  |
|-----------------|--------------|--------------|
| Semantic color classes | Stylesheet vars | Hex values |

**Comment by paulcpederson** [comment]
I think we could also think about listing WCAG 2.0 color combinations. Sort of like https://polaris.shopify.com/visuals/colors#color-combinations

**Comment by paulcpederson** [comment]
After talking this over with Creative Lab it seems like there is going to be a higher-level of documentation that exists for Calcite as a whole. I don't think CW will own the colors part of this. I'm closing for now, if it turns out we need to document this we can reopen.
