### ISSUE TITLE
Add pattern for mobile friendly side navs

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#757]
@paulcpederson I was discussing this issue with @eleanorh today. We need to have a pattern for making the `side-nav` mobile friendly. We are starting to see more users on smaller devices and need to figure out how to make this content accessible. This also relates to https://github.com/Esri/calcite-web/issues/623 which was for adding some kind of filterable side nav.

You can see this problem on the Calcite Web docs too. Do you think you and @oknoway might have time to prototype something we can launch for dev summit?

![calcite_web___esri_design_patterns_ _and_untitled-1_-_developers-site](https://cloud.githubusercontent.com/assets/378557/21667668/cc3f467a-d2af-11e6-91dd-e24bf41460f3.png)

**Comment by paulcpederson** [comment]
@patrickarlt for the calcite web docs I just experimented with using a select with our `js-select-nav` pattern. It's sort of a cop-out but it was fast and effective.

I've deployed it so you can see it in action:
http://esri.github.io/calcite-web/documentation/type/

**Comment by jmdye** [comment]
You could forgo the dropdowns and use the drawer as well. I tend to use the dropdowns like Paul suggested though.
![screen shot 2018-01-31 at 3 51 34 pm](https://user-images.githubusercontent.com/12836703/35647003-30275636-069f-11e8-912a-5485a466d95c.png)

**Comment by macandcheese** [comment]
Doing some issue cleanup - This should be addressed but possibly in Calcite Components or Calcite App Components? Closing here for now.
