### ISSUE TITLE
Two buttons in card

### ISSUE THREAD

**Issue by ajbroadbent** [Esri/calcite-web#759]
We're having a weird issue I can't figure out, and I was hoping you might be able to shed some light on it.  If you go to http://doc.arcgis.com/en/collector/, you'll see that two of the cards have two buttons instead of one.  They're side by side.  They look fine on this page.  BUT, if you look closely, you'll see that the two buttons are actually one pixel higher than the single buttons.  That's not a huge deal, just something to note.  The bigger issue is that when that card has less text in the p tag, the two buttons have a pixel of empty space between their bottom borders and the bottom border of the card.  Is there a way to make that not happen without just making the p text longer on cards that have two buttons?

Buttons with long p text:
![image](https://cloud.githubusercontent.com/assets/20780983/21900225/ecf6d358-d8a7-11e6-97ae-c6d1172c8fce.png)

Buttons with short p text (since there are two cards with two buttons on this page, you have to shorten the text on both of those cards to see the effect):
![image](https://cloud.githubusercontent.com/assets/20780983/21900273/12bc3b82-d8a8-11e6-8bad-1479694f63b0.png)

**Comment by ajbroadbent** [comment]
If you add a bottom padding of 6px, it seems to fix it, but that seems too hacky to me.  I assume there has to be a better solution.

**Comment by paulcpederson** [comment]
@ajbroadbent I didn't really design the buttons to go *outside* the `card-content`. But with two buttons I think the way you're doing it does look better. 

I just added `display: flex` to the `nav` element and that seems to help, so maybe give that a shot?

**Comment by paulcpederson** [comment]
I'm not sure why it's `1px` off though, maybe because the grouped buttons are floated?

In any case good 👀 !

**Comment by ajbroadbent** [comment]
I'll try that.  I assumed this method was a little unorthodox.  It's what the author figured out to fit two buttons side by side in a card.  Is there a better way to fit two buttons side by side at the bottom of a card?

**Comment by paulcpederson** [comment]
I don't think there is a better way. We could develop a way to do this nicely in the framework, though.

**Comment by ajbroadbent** [comment]
Thanks! For now I'll just use the flex display.  That seems to work beautifully.
