### ISSUE TITLE
Add the upper corner modifier-name as a Calcite-Web Component

### ISSUE THREAD

**Issue by fgarofalo10** [Esri/calcite-web#760]
On the documentation pages, there is a `<code class="modifier-name">.btn-large</code>` html snippet and the related CSS class ( `.styleguide-modifiers .styleguide-modifier-example .modifier-name` ) - could this be a component added into the Calcite-Web framework so it could be used with Panel components. Perhaps with additional modifier classes for upper left or upper right.

@paulcpederson - thoughts?

**Comment by paulcpederson** [comment]
I don't think this style is common enough to distribute with the actual framework.
