### ISSUE TITLE
Grouped Radio Button

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-web#762]
CAN I HAS?

[Kinna like-a dis?](http://codepen.io/paulcp/pen/rjWZwp)

@paulcpederson 
> essentially just a more button-y radio group

**Comment by paulcpederson** [comment]
Sketched a couple options for this:

http://codepen.io/paulcp/pen/rjWZwp/

<img width="304" alt="screen shot 2017-01-17 at 3 37 19 pm" src="https://cloud.githubusercontent.com/assets/1031758/22044730/f0785df4-dcca-11e6-91e6-1c8896ac1969.png">

and

http://codepen.io/paulcp/pen/bgBxae


<img width="448" alt="screen shot 2017-01-17 at 3 37 32 pm" src="https://cloud.githubusercontent.com/assets/1031758/22044731/f08189a6-dcca-11e6-9a73-4693cf9731e3.png">

**Comment by asangma** [comment]
😻

**Comment by asangma** [comment]
But yeah...I am cool with the light blue stuff.  
Can we reduce the font size for these dudes?  Or would that be breaking a pattern?

**Comment by paulcpederson** [comment]
I think we *should* reduce the font size. Other form elements I think use `font-size--1` and `font-size--2`

**Comment by paulcpederson** [comment]
updated codepen with more "calcite-web-y" class names: https://codepen.io/paulcp/pen/NvvbPg?editors=1100

**Comment by paulcpederson** [comment]
This could potentially be part of the "calcite-apps" set instead of core.

☝️ @julio8a

**Comment by paulcpederson** [comment]
This will be part of v1.2.0, which should be out sometime next week
