### ISSUE TITLE
Should alerts be full width?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#767]
@paulcpederson I keep coming across cases where I want to use the `.alert` component but I want it to stretch across the full width of the container. Shouldn't this be the default?

**Comment by paulcpederson** [comment]
This would allow developers to create alerts with really long line lengths, hindering readability. 

A modifier that just adds `max-width: none` would satisfy what you need, right? `alert-full` or something?

**Comment by patrickarlt** [comment]
`alert-full` would be fine.
