### ISSUE TITLE
IE11: Potential Rounding Error when using .card inside .block-group

### ISSUE THREAD

**Issue by oknoway** [Esri/calcite-web#769]
When a border is on a child of `.block-group`, the `flex-basis` and `width` values need the border-width added to the `calc()` statement.

#### Might be fixable with `box-sizing: border-box`.

- https://github.com/ArcGIS/arcgis-for-developers/issues/4644
- Fixed in https://github.com/ArcGIS/arcgis-for-developers/commit/bc4c16702a4d67b0529f639f78beb7043efe945f

**Comment by paulcpederson** [comment]
I'm going to close this as there is now apparently no border on cards? And it already has `box-sizing: border-box` which it inherits from the `block` class.
