### ISSUE TITLE
Indicator bar on second tier nav is confusing

### ISSUE THREAD

**Issue by TamaraYoder** [Esri/calcite-web#775]
This was brought up during an internal review of our redesigned Living Atlas website- Active page and hover have the same blue bar so can be confusing (in this example, I’m on the Home page and hovering over Benefits. Looks like both pages are active).
![014e9490-e6f8-11e6-8388-5f93e1097f87](https://cloud.githubusercontent.com/assets/11525122/23234055/b3b64da2-f905-11e6-963b-8f471b57c18f.png)

**Comment by paulcpederson** [comment]
Yes, the active indicator is the same as hover. But I should point out that `:hover` is supposed to also use the blue for it's text color. I'm guessing some of the overrides you've added to the top nav removed this behavior? There should also be a gap between the nav items? 

Open to suggestions as to the styling of the hover/focus state, though.

**Comment by TamaraYoder** [comment]
Adding @sanjibpanda and @ChrisMahlke to this conversation, as they are the developers for the site.

Can you please answer @paulcpederson 's question above?

**Comment by sanjibpanda** [comment]
Yes, There should be a gap between the nav items. We can make it happen with a minor fix. I think intentionally we have replaced (replaced with white) default :hover blue color text as it was not looking good on black background.

**Comment by paulcpederson** [comment]
@TamaraYoder You could change the border color for hover, or add a slight translucent background on hover maybe. I think since this is pretty custom to Living Atlas I'm going to close this issue. Feel free to reopen, though if there is a change in Calcite Web I can make to help with this.
