### ISSUE TITLE
Feature Request: Add a page with full list of css classes in docs

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-web#782]
I think a useful feature for the documentation would be having a reference page with the full list of the available css classes. Not sure exactly what design would be best, but it could just be something like all of the `Modifier` sections of each doc page all put together in a large, filterable list (like the icon search filter).

cc @oknoway

**Comment by paulcpederson** [comment]
@noahmulfinger this is a good idea. What would you expect the url of this page to be? And how would you expect to get there?

Maybe `http://esri.github.io/calcite-web/quick-reference/` or `http://esri.github.io/calcite-web/modifiers/` or something? With a link in the top nav? 

Not sure if it would work but we could also do this in the search overlay itself maybe? 

![sketch](https://cloud.githubusercontent.com/assets/1031758/23810638/3fecc3a4-0587-11e7-9efa-602525a41c9c.jpg)

**Comment by paulcpederson** [comment]
Each header there would be links as well, obviously

**Comment by asangma** [comment]
"CSS Cheatsheet"?

**Comment by paulcpederson** [comment]
To cast your vote for the name of this page, add an emoji reaction to this comment:

⚡️  Quick Reference
👻  Cheat Sheet

@oknoway @patrickarlt @noahmulfinger @asangma @araedavis

**Comment by paulcpederson** [comment]
assigning to @oknoway as I think he's working on this ✨  like a boss ✨

**Comment by oknoway** [comment]
If by `boss` you mean, repeatedly banging his head against a terminal until something happens… then, yeah.

**Comment by paulcpederson** [comment]
🎉  http://esri.github.io/calcite-web/quick-reference/ 🎉

**Comment by asangma** [comment]
Wooo!
