### ISSUE TITLE
Add .js-sticky to Docs

### ISSUE THREAD

**Issue by nullrocks** [Esri/calcite-web#784]
There is no documentation for .js-sticky

```html
<div class="js-sticky scroll-show tablet-hide" data-top="46">
    <button type="button" class="btn btn-clear" ng-click="goTop()">Back to Top</button>
</div>
```

Also, sometimes it does not update it's state/position causing this:
![screen shot 2017-03-13 at 12 12 31 pm](https://cloud.githubusercontent.com/assets/1198518/23869008/88de1bfc-07ef-11e7-84ef-76f3cea86fec.png)

**Comment by paulcpederson** [comment]
OK, I just found where the sticky docs are: http://esri.github.io/calcite-web/documentation/grid/#scroll-sticky

I think we should probably mention this in the javascript tab as well.
