### ISSUE TITLE
Trap keyboard focus in modals

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#793]
I could have sworn that this already worked, but currently when you open a modal, we don't "trap" the keyboard focus and keep it in that modal. This is an accessibility requirement.

Maybe this broke in a recent release?

**Comment by patrickarlt** [comment]
@paulcpederson FWIW I've been using https://allyjs.io/ for this stuff lately, its a little heavy but it handles lots of fun edge cases and is pretty easy to work with.

**Comment by jimmieego** [comment]
I came across a talk by Marcy Sutton yesterday (https://vimeo.com/251520898) in which she mentioned the `inert` attribute for modals. It's not in HTML spec yet but here is the [description](https://github.com/WICG/inert) and a [polyfill](https://github.com/GoogleChrome/inert-polyfill).

**Comment by paulcpederson** [comment]
@jimmieego that is a really nice solution to this problem.

**Comment by paulcpederson** [comment]
will be fixed in next release.
