### ISSUE TITLE
If you resize the browser window while search is open, search/close icons get mismatched

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#794]
1. start large
2. open search
3. make browser window smaller (tablet size)
4. Notice top icon is now search instead of close:

![screen shot 2017-03-27 at 12 41 18 pm](https://cloud.githubusercontent.com/assets/1031758/24374883/4f47fb72-12eb-11e7-8eb8-4bef58ccea26.png)

**Comment by paulcpederson** [comment]
I think we will be moving towards using the global nav for search + top nav, so I'm adding this to v1 and hopefully it will get taken care of when we move over.

**Comment by macandcheese** [comment]
Closing this - should be fixed for global nav.
