### ISSUE TITLE
Need to update Avenir to new font family declarations

### ISSUE THREAD

**Issue by sympletech** [Esri/calcite-web#797]
**New StyleSheet**
http://fast.fonts.com/cssapi/ce1d92e6-a07d-4298-8523-37e4a616768e.css

**New Font Family Names**
'Avenir Next W05 Heavy Italic'
'Avenir Next W05 Heavy'
'Avenir Next W05 Bold Italic'
'Avenir Next W05 Bold'
'AvenirNextLTW02-DemiIta'
'Avenir Next W05 Demi'
'Avenir Next W05 Medium Italic'
'Avenir Next W05 Medium'
'AvenirNextLTW02-Italic'
'AvenirNextLTW02-Regular'
'AvenirNextW02-LightItal'
'Avenir Next W05 Light'
'Avenir Next W05 Thin Italic'
'Avenir Next W05 Thin'
'Avenir Next W05 Ultra Light'
'Avenir Next W05 Ultra Light It'

**Comment by sympletech** [comment]
These changes have been submitted in PR - https://github.com/Esri/calcite-web/pull/801

**Comment by jonathantneal** [comment]
@paulcpederson, now that #807 has been merged and [RC5](https://github.com/Esri/calcite-web/releases/tag/v1.0.0-rc.5) is shipped, does this mean this may be closed?

**Comment by paulcpederson** [comment]
YES!
