### ISSUE TITLE
Modal content still using text-align:start; not supported in I.E.

### ISSUE THREAD

**Issue by vijayendranj** [Esri/calcite-web#798]
#503 
![screen shot 2017-04-04 at 11 27 49 am](https://cloud.githubusercontent.com/assets/6799595/24672516/e34e05a2-1929-11e7-91b0-3b83b73d0713.png)

**Comment by patrickarlt** [comment]
Since `text-content: start;` isn't supported in IE 11 this makes it so all the text in modals is centered in IE.

![screenshot 2017-05-12 08 16 58](https://cloud.githubusercontent.com/assets/378557/26006470/59d68b88-36f1-11e7-8242-514cc020f2d3.png)

**Comment by TifPun** [comment]
Hello, I wonder if there's an estimate on when the bug can be fixed? Or is there a workaround to get the text alignment working in IE? Currently this is affecting many places in our app (Operations Dashboard for ArcGIS). Thanks in advance!

**Comment by paulcpederson** [comment]
@TifPun I'll try to get this into the next release. For now, it would be easy to add a workaround in your app. Just add the following CSS:

```
.modal-content {
  text-align: left;
}

html[dir="rtl"] .modal-content {
  text-align: right;
}
```

**Comment by TifPun** [comment]
Thanks for the quick response and the workaround @paulcpederson! When is the next release going to happen?

**Comment by paulcpederson** [comment]
Probably sometime in the next couple weeks

**Comment by paulcpederson** [comment]
https://github.com/Esri/calcite-web/releases/tag/v1.0.0-rc.6
