### ISSUE TITLE
Firefox Windows – Checkbox border

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#802]
When using Firefox on Windows, clicking on a checkbox applies a strange border. Goes away once you click away anywhere.

However, it looks pretty bad when utilizing checkboxes. screenshot below.

![image](https://cloud.githubusercontent.com/assets/6144462/25256588/b9d76d52-25e6-11e7-9ec5-3212869d11a3.png)

**Comment by paulcpederson** [comment]
@julio8a weird. That was a pretty normal focus state before. I'm assuming firefox changed something about their `auto` outline value. Removing the `auto` declaration fixes it. I'll try to get this in the next release.
