### ISSUE TITLE
Dropdowns don't have enough contrast against the background

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#803]
Darkening the border of dropdown menus to `#ddd` and slightly darkening the box-shadow would go a long way towards making the menu feel more like it's "floating" *above* content. 

Currently the style is not distinct enough, and the menu looks chaotic and hard to pick out.

**Comment by macandcheese** [comment]
Related https://github.com/Esri/calcite-web/issues/943

**Comment by paulcpederson** [comment]
This will be updated with the new design standards for depth/float. Closing.
