### ISSUE TITLE
.input-minimal background should be transparent

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-web#804]
The `input-minimal` class is inheriting the white background from `input`. It should be transparent.

https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/components/_form.scss#L13

@asangma

**Comment by paulcpederson** [comment]
@TheBlueDog agree.

**Comment by asangma** [comment]
@TheBlueDog 
![coin](https://cloud.githubusercontent.com/assets/12503298/25297228/51744f9e-26a1-11e7-9875-a73b8a71dd84.gif)
