### ISSUE TITLE
margin-left-1 class adding extra margin for rtl pages

### ISSUE THREAD

**Issue by ajbroadbent** [Esri/calcite-web#805]
On pages that are rtl instead of ltr, the margin-left-1 class adds both a left margin and a right margin instead of just adding a right margin.  This is occurring in version 1.0.0-beta.33.

![image](https://cloud.githubusercontent.com/assets/20780983/25395838/4725ad1e-2997-11e7-9d50-41fb51c912ec.png)
![image](https://cloud.githubusercontent.com/assets/20780983/25395874/66e13a1a-2997-11e7-876e-613cec888e1e.png)

**Comment by HeathMeyette** [comment]
Assigning to Tim. @tim-white-esri please feel free to reassign to your team members that have additional bandwidth.

**Comment by paulcpederson** [comment]
I think we can get around this by scoping all pre and post (even in left to right) to a `dir`. Example:

```
/* left to right, or no direction */
html:not([dir]) .pre-X, html[dir="ltr"] .pre-X {
   margin-left: X;
}
/* right to left */
html[dir="rtl"] .pre-X {
 margin-right: X;
}
``` 

This will add selectors, but will eliminate the bug.

**Comment by paulcpederson** [comment]
Will be fixed in the next release
