### ISSUE TITLE
pre-X overridden by :first-child selector above 1525.5px 

### ISSUE THREAD

**Issue by tim-white-esri** [Esri/calcite-web#806]
For columns, the "pre-x" is not defined for larger views. The styles apply only between 860px and 1524.5px:

```
@media screen and (max-width: 1524.5px) and (min-width: 860px)
calcite-web.min.css:1
[class*="column-"] .pre-4[class*="column-"]:first-of-type {
    margin-left: 15.83333vw;
}
```

With the upper limit of 1524.5px, anything above that loses the `margin-left` offset causing the content to shift to the left.

The upper limit should be removed. Also suggest removing the subpixel from media queries. 

This is verified for `class="pre-4"` and can be seen http://www.esri.com/videos . Scroll to bottom of page, the About Esri section will be centered until screen width exceeds 1525px.

**Comment by paulcpederson** [comment]
This is actually a specificity bug dealing with the `:first-child` pseudo-selector. We do want the media query to end, but the larger media query needs to apply styles to the `first` and `last` child selectors as well. Will add to next release.

**Comment by paulcpederson** [comment]
will be part of next release.
