### ISSUE TITLE
Incorrect directory path for file loader-ie9.gif

### ISSUE THREAD

**Issue by jasonhett** [Esri/calcite-web#813]
Paths for loader-ie9.gif try to resolve to '../img/img/loader-ie9.gif' but file is located at '../img/loader-ie9.gif'

![screen shot 2017-06-01 at 8 37 35 am](https://cloud.githubusercontent.com/assets/6620345/26680019/9fe43bd4-46a5-11e7-881d-7badb650b112.png)

**Comment by paulcpederson** [comment]
I'm tempted to drop this as I think platform-wide we are moving to IE10/11+. I'll look into that and at the very least fix the image path. Thanks, @jasonhett

**Comment by jasonhett** [comment]
Sounds good to me. I'm not using the ie9 gif, webpack just complains when bundling.
