### ISSUE TITLE
Avenir Next font requests cause CORS errors

### ISSUE THREAD

**Issue by hitdrumhard** [Esri/calcite-web#819]
What is the correct way to request a copy of this font to install locally? 

Also, for our actual deployment tiers, how do we resolve this?
Access to Font at 'https://api2.fonts.com/FontSubsetter.ashx?d44f19a684109620e484157aae90e8188…%A2%E2%82%AC%C2%9D&ot=false&projectId=2abe0dd7-8964-459a-9f40-70d8f5504a30' from origin 'http://etcdev.esri.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '**http://etcdev.esri.com**' is therefore not allowed access. The response had HTTP status code 403.

**Comment by paulcpederson** [comment]
This has come up in several different environments. We recently moved to a new font service and now we're getting this CORS error in certain cases. One of two things is happening:

1. The domain whitelist works differently and doesn't accept wildcards (ie. `*.esri.com` no longer covers `etcdev.esri.com`
2. The way we've integrated the font service causes this error. 

Either way we are looking into the problem and will try to solve before the next release. In the meantime you can send me an email and I'll help you set up fonts locally in your project using the `calcite-web-no-fonts` bundle.

**Comment by jonathantneal** [comment]
Have you presented these issues to Monotype? We request the exact same URL they gave us. I only see these scenarios:

1. Their whitelisting is broken, as you mentioned.
2. They errantly require the CSS file making the request for the font files reside on their server.

Nothing else about our integration could have an effect that I know of.

**Comment by paulcpederson** [comment]
@jonathanan I agree, I think it's most likely the second option, so we should work with them to figure out if that's something we can fix.
