### ISSUE TITLE
Missing figcaption

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#827]
At http://esri.github.io/calcite-web/examples/core/, I noticed the card examples use a `figure` element, but do not use a `figcaption` element even though the classname is `caption`. Is this on purpose?

```html
<figure class="card-image-wrap">
	<img class="card-image" src="../../assets/img/docs/bridge3.jpg" alt="Bridge Club, 1954">
	<div class="card-image-caption">
		Florida, January 1954
	</div>
</figure>
```

Would you like a PR to change these to something like the following?

```html
<figure class="card-image-wrap">
	<img class="card-image" src="../../assets/img/docs/bridge3.jpg" alt="Bridge Club, 1954">
	<figcaption class="card-image-caption">
		Florida, January 1954
	</figcaption>
</figure>
```

**Comment by paulcpederson** [comment]
@jonathantneal not intentional, that would be a good change.
