### ISSUE TITLE
Proposal: Audio Player / Toolbar

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#828]
I’m working on an audio player, and I noticed there aren’t many small accessible audio players on the web. So, would this be something you’re at all interested in adding to Calcite?

**Source**:

https://github.com/jonathantneal/audio-player

**Demos**:

https://jonathantneal.github.io/audio-player/
https://jonathantneal.github.io/audio-player/rtl.html

**Comment by paulcpederson** [comment]
@jonathantneal is there a reason you didn't use the `<audio>` element for this?

**Comment by jonathantneal** [comment]
@paulcpederson, hard to answer. I used the audio element for this. The source of the page, in the first example, is:

```html
<audio src="http://www.noiseaddicts.com/samples_1w72b820/2534.mp3" controls></audio>
```

**Comment by paulcpederson** [comment]
@jonathantneal ah, ok, so you're just replacing the audio player with custom markup via the AudioPlayer JavaScript?

**Comment by jonathantneal** [comment]
Exactly. This way, you are writing what you mean, and even if the JS fails, there is a working Audio Element.

**Comment by paulcpederson** [comment]
After discussions it seems like an Audio or Video player fall outside the responsibility of Calcite Web. Should be its own shared component with single responsibility.
