### ISSUE TITLE
IE/Edge Input Bug

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#829]
We're getting a bug in IE11/Edge

for some reason the background color is not changing. One of our devs was able to fix this, but he pointed it could be a CW issue, can you look into this?

dev fix cleared everything but the bg color. Therefore, there could be other CSS properties in CW causing issues?

dev fix:
https://jsfiddle.net/g90vu7z7/

issue screenshot:
![image](https://user-images.githubusercontent.com/6144462/27877492-b895d374-616f-11e7-807c-dbd34d79a787.png)

**Comment by paulcpederson** [comment]
@julio8a I just briefly looked into this, and it seems like it's set up properly in calcite web to use the Sass variable `$white`, which is converted to black in the dark stylesheet. If you look at the generated CSS it's correct: https://github.com/Esri/calcite-web/blob/master/dist/css/calcite-web-dark.css#L4705 (sets input's background color to black) so I'm wondering if something else is going on?

**Comment by julio8a** [comment]
Yeah, it's only on IE

it is CW, here is sample:
https://jsfiddle.net/g90vu7z7/

**Comment by paulcpederson** [comment]
@julio8a found it. Fix will be part of the next release.
