### ISSUE TITLE
Deprecate IE8 Grid Fallbacks?

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#836]
I’m not sure what’s involved with this task, but there is some IE8 functionality in the grid system.

Are `$ie8-support` or `$column-gutter-fallback` still available? Are they needed or even recommended?

As seen at:
- http://esri.github.io/calcite-web/documentation/grid/#configuration
- https://github.com/Esri/calcite-web/blob/master/docs/source/documentation/grid/_configuration.md

**Comment by paulcpederson** [comment]
@jonathantneal I'll have to look into this to see if it just needs to be removed from the docs, or if there are actual checks for that variable. I agree we should remove (deprecate) them.

**Comment by paulcpederson** [comment]
@tim-white-esri if somebody on your team is in editing the grid code, this might be a good bit of cleanup as well.

**Comment by jonathantneal** [comment]
👍
