### ISSUE TITLE
Toggle UI

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#837]
I think it would be useful to have a toggle inside Calcite-Web (see screenshot below). We are looking to leverage this on Operations Dashboard. It's already being utilized in AGOL, we should add it to CW so that web apps can use it. It'll also increase the level of consistency between web apps and AGOL.

![image](https://user-images.githubusercontent.com/6144462/28440408-faf80416-6d5a-11e7-9b43-027919d53d15.png)

**Comment by julio8a** [comment]
Maybe this falls under the same category?

# sliders
some examples from the web:
![cac8da1a-41f7-11e7-9698-8a2274913acc](https://user-images.githubusercontent.com/6144462/28441408-6f439ec6-6d5f-11e7-9620-c0253f1751b6.png)
![b85897ee-41f7-11e7-9a81-bacd67c77e0c](https://user-images.githubusercontent.com/6144462/28441407-6f3fc18e-6d5f-11e7-87ef-7c62c776a212.png)
![97ee7a14-41f7-11e7-8fe1-bde08d0ac4c8](https://user-images.githubusercontent.com/6144462/28441406-6f3ec928-6d5f-11e7-847b-3df7a1bb8c76.png)

**Comment by paulcpederson** [comment]
@julio8a I styled the range input in ArcGIS Online, and I could port that over as well:

<img width="516" alt="screen shot 2017-07-20 at 3 46 09 pm" src="https://user-images.githubusercontent.com/1031758/28442011-c8815aca-6d62-11e7-8136-22c7040015ff.png">

**Comment by paulcpederson** [comment]
The range slider only allows for one input, though, so if you need multiple stop points that would have to be a custom element that would require javascript.

**Comment by jonathantneal** [comment]
I was just working on something like this (for the original request, a checkbox as a switch): https://s.codepen.io/jonneal/debug/BZXadw#forms

I’m working on a container based version for Edge compatibility. For now, it can be demo’d in Chrome, Safari, Firefox, etc. (anybody but Edge/IE, sadly)

Thoughts?

**Comment by paulcpederson** [comment]
@jonathantneal the one I made for Online works in Edge (but there is an extra div).

HTML:

```
<label class="filter-toggle clearfix">
      <span class="filter-toggle-label left font-size--1 inline-block">Setting text</span>
      <input type="checkbox" class="filter-toggle-input" checked>
      <span class="filter-toggle-switch right"></span>
</label>
```

CSS:

```
/* Prominent on/off switch component */
.filter-toggle {
  display: block;
  position: relative;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
  tap-highlight-color: transparent;
}

.filter-toggle-input {
  opacity: 0;
  position: absolute;
}

.filter-toggle-label {
  width: calc(100% - 3rem);
}

.filter-toggle-switch {
  position: relative;
  display: inline-block;
  width: 2rem;
  height: 1.25rem;
  background: white;
  box-shadow: inset 0 0 0 0.0625rem #ccc;
  border-radius: 0.65rem;
  vertical-align: -0.3rem;
  transition: all 0.40s cubic-bezier(.17,.67,.43,.98);
  margin-top: 0.15em;
}

.filter-toggle:active .filter-toggle-input + .filter-toggle-switch,
.filter-toggle-input + .filter-toggle-switch:active {
    box-shadow: inset 0 0 0 0.73rem #ccc;
}

.filter-toggle-switch:after {
  position: absolute;
  display: block;
  content: '';
  width: 1.175rem;
  height: 1.175rem;
  border-radius: 0.75rem;
  top: 0.025rem;
  left: 0.025rem;
  background: white;
  box-shadow: inset 0 0 0 1px #ccc, 0 0 0.05rem rgba(0,0,0,0.05), 0 0.1rem 0.2rem rgba(0,0,0,0.2);
  transition: all 0.25s ease-out;
}

.filter-toggle:active .filter-toggle-input + .filter-toggle-switch:after,
.filter-toggle-input + .filter-toggle-switch:active:after {
    width: 1.15rem;
}

.filter-toggle-input:checked + .filter-toggle-switch {
    box-shadow: inset 0 0 0 0.73rem #0079c2;
}

.filter-toggle-input:checked + .filter-toggle-switch:after {
    left: 0.775rem;
}

.filter-toggle:active .filter-toggle-input:checked + .filter-toggle-switch:after,
.filter-toggle-input:checked + .filter-toggle-switch:active:after {
    left: 0.4375rem;
}

.esriRtl .filter-toggle-switch:after {
  left: auto;
  right: 0.025rem;
}

.esriRtl .filter-toggle-input:checked + .filter-toggle-switch:after {
    left: auto;
    right: 0.775rem;
}

.esriRtl .filter-toggle:active .filter-toggle-input:checked + .filter-toggle-switch:after,
.esriRtl .filter-toggle-input:checked + .filter-toggle-switch:active:after {
    left: auto;
    right: 0.4375rem;
}

/* focus styles for accessibility */
.filter-toggle-input:focus + .filter-toggle-switch {
  box-shadow: inset 0 0 0 0.0625rem #ddd, 0 0 1px 2px #bbb;
}

.filter-toggle-input:checked:focus + .filter-toggle-switch {
  box-shadow: inset 0 0 0 0.73rem #0079c2, 0 0 1px 2px #bbb;
}
```

**Comment by jonathantneal** [comment]
Sweet! Do you have a convention you prefer when components require additional DOM?

**Comment by paulcpederson** [comment]
No, not really.

**Comment by paulcpederson** [comment]
@jonathantneal do you know of a convention? I'm all 👂

**Comment by paulcpederson** [comment]
This could potentially be part of the "calcite-apps" set instead of core.

☝️ @julio8a

**Comment by jmdye** [comment]
Certainly the range slider would be more appropriate in "calcite-apps", the toggle could be useful for Yes/No or True/False answers on a form
