### ISSUE TITLE
Style the "range" input

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#838]
from #837 , we should have styles that work for the range input. In ArcGIS Online looks like this:

![screen shot 2017-07-21 at 9 42 54 am](https://user-images.githubusercontent.com/1031758/28473379-203e2356-6df9-11e7-9331-a39a270f28cf.png)

Uses the following styles:

```
/* chrome/safari */
input[type="range"] {
  border: 1px solid transparent;
  box-shadow: none;
  margin-top: 0;
}

input[type="range"]::-webkit-slider-runnable-track {
  width: 100%;
  height: 10px;
  background-color: #efefef;
  border: 1px solid #ccc;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.15);
  border-radius: 6px;
}

input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  border: 2px solid #ccc;
  box-shadow: 0 0 4px rgba(0,0,0,0.05);
  height: 22px;
  width: 22px;
  border-radius: 50%;
  background: #fff;
  margin-top: -6px;
}

input[type="range"]:focus {
  outline: none;
}

input[type="range"]:focus::-webkit-slider-thumb {
  outline: auto;
}

/* firefox */
input[type="range"]::-moz-range-track {
  width: 100%;
  height: 10px;
  background-color: #efefef;
  border: 1px solid #ccc;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.15);
  border-radius: 6px;
}

input[type="range"]::-moz-range-thumb {
  -webkit-appearance: none;
  border: 2px solid #ccc;
  box-shadow: 0 0 4px rgba(0,0,0,0.05);
  height: 22px;
  width: 22px;
  border-radius: 50%;
  background: #fff;
  margin-top: -6px;
}

input[type="range"]:focus::-moz-range-thumb {
  outline: 1px dotted #007ac2;
}

/* microsoft */
input[type="range"]::-ms-track  {
  width: 100%;
  height: 10px;
  background: transparent;
  border: 1px solid #ccc;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.15);
  border-radius: 6px;
  color: transparent;
}

input[type="range"]::-ms-fill-lower {
  background: #efefef;
  border-radius: 6px;
}
input[type="range"]::-ms-fill-upper {
  background: #efefef;
  border-radius: 6px;
}

input[type="range"]::-ms-thumb {
  -webkit-appearance: none;
  border: 2px solid #ccc;
  box-shadow: 0 0 4px rgba(0,0,0,0.05);
  height: 22px;
  width: 22px;
  border-radius: 50%;
  background: #fff;
  margin-top: -6px;
}

input[type="range"]:focus::-ms-thumb {
  outline-width: 1px;
  outline-style: dashed;
}
```

**Comment by jgrayson-apl** [comment]
Is this going to be done via a new class or is calcite taking over all input[type="range"] elements?

**Comment by paulcpederson** [comment]
@jgrayson-apl the primary issue to fix is that currently, the range styles are broken, so this will be applied to `input[type="range"]`. We could create a class, though, very open to that.

**Comment by jgrayson-apl** [comment]
@paulcpederson Thank you for the clarification.  I've been thinking about this and I'm not sure we need a class as most 'slider' widgets I've seen implement their own UX and don't necessarily reuse an input[type="range"] so conflicts with other widgets seems unlikely (compared to other elements such as tables and labels).  Classes that abstract the browser specific details of the internal components would be nice, but not necessary.  Thank you.

**Comment by jgrayson-apl** [comment]
Will we have different styling when using the dark theme?

![image](https://user-images.githubusercontent.com/5324720/33694579-baf47c3a-daad-11e7-874d-747f83e5d5a5.png)

**Comment by paulcpederson** [comment]
@jgrayson-apl yeah for the actual implementation these will use the color Sass variables, which automatically invert for the [dark theme](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web-dark.scss).

**Comment by macandcheese** [comment]
PR @ https://github.com/Esri/calcite-web/pull/891
