### ISSUE TITLE
arrow-down, arrow-left: not the same

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#839]
**down-arrow** is not an **arrow**. It is a **triangle**. There is no down-facing arrow. There _is_ a left-facing **triangle** called **left-triangle-arrow**.

Perhaps these naming conventions could be tidied up?

I recommend first keeping them consistent among themselves, and then possibly just calling them the one thing they are. A triangle is a triangle. An arrow is an arrow.

**Comment by asangma** [comment]
Indeed. This something we need to work on with the icon team.
We can also consider aliases for backwards compatibility.

**Comment by macandcheese** [comment]
Doing some issue pruning... @julio8a thoughts on deprecating the icons in CW and enforcing use of https://github.com/ArcGIS/calcite-ui-icons ? There seems to be some overlap between the two sets and it'd be nice to consolidate and use one.

**Comment by julio8a** [comment]
@macandcheese, All the icons from CW are in the calcite-ui-icons repository. I talked with @paulcpederson yesterday and we discussed adding a deprecation message for the icons in CW. 

deprecation message we used in arcgis-apps-icons:
```
DEPRECATED
Please migrate to: calcite-ui-icons
The arcgis-apps-icons repository along with the reference page will be deleted on 9/14/2018.
```

**Comment by paulcpederson** [comment]
We should open a separate issue for moving to calcite-ui-icons. This issue can be closed as we won't control naming anymore.
