### ISSUE TITLE
blue button border color should still match background color on hover

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#840]
Discussing with @bstifle, he mentioned the blue border should change the same dark blue color as the background when it is active/hovered.

**Comment by paulcpederson** [comment]
Is that... an issue?

**Comment by bstifle** [comment]
well, yes imo. :)

it starts with no visual border

and the hover state then shows a border.

inconsistent with other hover states throughout CW

**Comment by paulcpederson** [comment]
@bstifle so desired behavior is for the border to change color as well?

**Comment by bstifle** [comment]
that makes more sense

**Comment by paulcpederson** [comment]
word up, 🏠 🍳

**Comment by paulcpederson** [comment]
Will be part of next release, nice work @macandcheese
