### ISSUE TITLE
Select multiple shouldn't have background color

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#842]
Multiple selects currently get the white background color, but it's rendered incorrectly. Example:

| Current | Without background white |
| --- | --- |
| ![screen shot 2017-07-27 at 12 05 55 pm](https://user-images.githubusercontent.com/1031758/28687714-27962250-72c4-11e7-94b8-4b9904f4d83a.png) | ![screen shot 2017-07-27 at 12 06 12 pm](https://user-images.githubusercontent.com/1031758/28687713-27917c82-72c4-11e7-83d4-534e466e998d.png) |

**Comment by macandcheese** [comment]
Unable to reproduce on my end... Is there any specific browser / OS this affects?

**Comment by paulcpederson** [comment]
@macandcheese I think chrome must have fixed this in a patch at some point. Seems good now.
