### ISSUE TITLE
Additional modifiers for search pattern and input-search

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#848]
Please add some additional modifiers for search pattern and input search so that we can use more appropriate search patterns for the component where it is being placed (second and third nav for example)

**`.search-accordion`**
![search-accordion](https://user-images.githubusercontent.com/12836703/30219033-cfd12998-9488-11e7-9131-fc8c06bdd089.png)

**`.input-search .search-toggle`** 
(Tailcoat top-nav site-search-input pattern. Click on search icon to reveal inline search-input)
![search-inline-expand](https://user-images.githubusercontent.com/12836703/30219104-0a109422-9489-11e7-87cc-94f7d447e0c6.png)

**Comment by paulcpederson** [comment]
There should only be one search pattern, and that is the search take over. 
![screen shot 2017-11-03 at 2 38 38 pm](https://user-images.githubusercontent.com/1031758/32396958-bb289d80-c0a4-11e7-823f-44e54d03e52f.png)

I don't think this will work in any other contexts. That being said, is this issue still relevant?

**Comment by jmdye** [comment]
I can't say I agree with the idea of one search pattern to rule them all, but no one else has indicated a need for multiple.
