### ISSUE TITLE
Misspelled presentaiton links in footer of doc site in gh-pages

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#849]
Caclite Web: A Primer
Caclute Web: Deep dive

**Comment by paulcpederson** [comment]
@jmdye thanks! will fix

**Comment by jmdye** [comment]
i misspelled my reporting of mispellings =(

**Comment by paulcpederson** [comment]
@jmdye very meta 😂

**Comment by paulcpederson** [comment]
pushed fix to doc site, thanks again @jmdye
