### ISSUE TITLE
Table Tag

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#852]
The fact that calcite web is directly taking ownership of the tag ‘table’ is really painful. It messes up with third-party library.This is a breaking change that we should take before calcite web 1.0 is released. This is really going to hurt a lot of apps if we don’t fix it now.

**Comment by paulcpederson** [comment]
@julio8a I would tend to agree. Thinking a class applied to the root table element would be a good in-between.

**Comment by julio8a** [comment]
The issue we're having is that table tag name and all children should not be modified by calcite.
If we want the table to be ‘calcite’, then we want to add a class like this:
```<table class='table table-blue'></table>```

**Comment by paulcpederson** [comment]
Yep. That's what my comment was going for, sorry if I was unclear. I feel your pain on this issue, it cause a whole bunch of problems when styling dojo widgets as well (they use table layouts everywhere).

**Comment by julio8a** [comment]
What would be the timeline for this change to take place in CW?

**Comment by paulcpederson** [comment]
I'm pretty maxed out right now, but maybe @tim-white-esri could devote some cycles from his team on this? It's a pretty straight forward change, just needs to be documented.

**Comment by paulcpederson** [comment]
I think this would be a good change. It's a breaking change, but I think it's the right call.

**Comment by jgrayson-apl** [comment]
I agree this would really help when using with the Esri JS API as I currently have several workarounds via JS to add the 'table-no-table' class to various use cases when esri js/dojo create tables on the fly (popups, legends, charts, etc).  This workaround helps some, but doesn't solve everything.  Also, <table> is not the only tag where this happens...

**Comment by jgrayson-apl** [comment]
I agree this would really help when using with the Esri JS API as I currently have several workarounds via JS to add the 'table-no-table' class to various use cases when esri js/dojo create tables on the fly (popups, legends, charts, etc).  This workaround helps some, but doesn't solve everything.  Also, <table> is not the only tag where this happens...

**Comment by paulcpederson** [comment]
Yeah other styles are default typography (`p`, `li`, `blockquote`, `h1...6`, `code`).

**Comment by jgrayson-apl** [comment]
yep... 'label' is one that always causes issues, but dealing the 'table' will help a lot, so thank you.

**Comment by tim-white-esri** [comment]
@paulcpederson Do you have this handled?

**Comment by paulcpederson** [comment]
@tim-white-esri there is an open pr (https://github.com/Esri/calcite-web/pull/858) which I think just needs a little doc, but other than that should be good to go.

**Comment by paulcpederson** [comment]
this will be part of the next release
