### ISSUE TITLE
Default btn and form field sizing inconsistent

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-web#853]
Upon close inspection it seems that the default form input fields vary between 38-39px height. The default button height is is 39px. Can we make these consistent?

**Comment by paulcpederson** [comment]
Can you give more examples of which are too big?

**Comment by TheBlueDog** [comment]
![screen_shot_2017-10-27_at_2_29_24_pm](https://user-images.githubusercontent.com/5419306/32119637-dccb3dd4-bb23-11e7-9c58-85f5e8c02cd4.png)

![screen_shot_2017-10-27_at_2_31_34_pm](https://user-images.githubusercontent.com/5419306/32119639-de3ee3aa-bb23-11e7-97e6-afff0f32c17f.png)

Also, the difference between the small and default buttons is not enough. We are using 36px and 39px. Bootstrap has a nice difference with 30px and 38px.

**Comment by paulcpederson** [comment]
agree re:small buttons we can shrink those more. 

The inputs have the exact same padding. Their not different, it's probably just a rounding issue. WE can move to use even pixels for padding on these
![screen shot 2017-10-27 at 11 38 20 am](https://user-images.githubusercontent.com/1031758/32119880-723effd6-bb0b-11e7-9e5e-a2ccca0b377d.png)
![screen shot 2017-10-27 at 11 38 27 am](https://user-images.githubusercontent.com/1031758/32119881-725009f2-bb0b-11e7-8411-4ca90b80d703.png)
![screen shot 2017-10-27 at 11 38 38 am](https://user-images.githubusercontent.com/1031758/32119882-726167f6-bb0b-11e7-8dc6-bb2089423114.png)

**Comment by TheBlueDog** [comment]
The goal would be that a default button and default inputs could be placed side by side and the heights match exactly.

**Comment by paulcpederson** [comment]
@TheBlueDog can you send a screenshot where that's not the case?

**Comment by TheBlueDog** [comment]
I built Sketch symbols for prototyping based on the day pages. This is where I noticed the difference. I don't have it in code yet.

**Comment by paulcpederson** [comment]
I think it won't happen in code. The rounding error comes when they fall in the middle of a pixel, chrome rounds down, or up depending on which is closest. But if they are inline with each other they will be rounded the same way, so shouldn't be an issue. 

When you code it, let me know if you see the problem and we can patch the button padding to be more explicit.
