### ISSUE TITLE
btn-clear should be...clear

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#854]
```.btn-clear``` sets a white background which is not the intent when its being used on a panel of any color other than ```.panel-white``` or any other colored element for that matter.
![screen shot 2017-11-02 at 7 05 27 pm](https://user-images.githubusercontent.com/12836703/32354645-fcbc0e98-c000-11e7-86a7-91d05d94d4d2.png)

Shouldn't the background property for ```.btn-clear``` be ```background: none;``` so that it's actually...you know, clear?
![screen shot 2017-11-02 at 7 05 48 pm](https://user-images.githubusercontent.com/12836703/32354648-01c6be24-c001-11e7-8dd8-0ff313c03840.png)

**Comment by paulcpederson** [comment]
They are white background because if you drop them on an off-white page they no longer pass WCAG 2.0 AA accessibility standards. It was changed to white background as part of this issue: https://github.com/Esri/calcite-web/issues/649.

Sorry for the confusion, @jmdye and thanks for the feedback!

**Comment by jmdye** [comment]
![image](https://user-images.githubusercontent.com/12836703/32375993-d6194476-c079-11e7-9136-de86328bfd95.png)
