### ISSUE TITLE
Latest Chrome Bug

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#857]
In the latest update of chrome buttons have rounded corners. We need to specify the border radius in calcite web so that chrome's default does not change our UI.

![image](https://user-images.githubusercontent.com/6144462/32855441-7b225bc6-c9f6-11e7-895b-13531d3d082a.png)

![image](https://user-images.githubusercontent.com/6144462/32855446-7f861fc2-c9f6-11e7-9c27-eca72368be96.png)

We need this fixed **ASAP** as our web apps are being affected.

**Comment by paulcpederson** [comment]
@julio8a I already fixed that in the most recent release a couple weeks ago https://github.com/Esri/calcite-web/releases/tag/v1.0.0-rc.8
