### ISSUE TITLE
Radio buttons on iPad

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#861]
Is this a Calcite Web issues? Dashboard devs are mentioning it is.

The radio buttons should look like radio buttons on iPad not checkboxes.
![image](https://user-images.githubusercontent.com/6144462/33337181-07bcc9ec-d427-11e7-860b-a61cdd237393.png)

**Comment by paulcpederson** [comment]
@julio8a yeah, that's a bug in calcite web, I just confirmed. Will look into this.

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-web/pull/890, made checked styling on iOS a bit more blatant as well.
