### ISSUE TITLE
Incorrect doc for modal:open

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-web#862]
When trying to open a modal via JS, doc says to pass in {id:"modalId"}:

modal:open | Opens a specific modal | {id: modalId } | openModal()

...but that throws an error.  In order to get it to work correctly I have to only pass in just the modal id:

calcite.bus.emit("modal:open", "my-modal-id");

**Comment by paulcpederson** [comment]
@jgrayson-apl this must be documented incorrectly, will fix.

**Comment by macandcheese** [comment]
Taking a look... **openModal** uses the `data-modal` attribute -  the **modalId** value in the function is set based on that value when the modal toggle is clicked.

@jgrayson-apl In the future we can better document what data attributes are needed to achieve functionality like this. Closing for now but happy to update if you have any specific changes.

**Comment by jgrayson-apl** [comment]
Adam, this is a documentation bug related to calling calcite.bus.emit(...).  All I'm asking is for is a simple update to the documentation so others don't go through the same pains. http://esri.github.io/calcite-web/documentation/javascript/

**Comment by macandcheese** [comment]
There's inconsistent syntax being used which makes the docs accurate for some components, but incorrect for others. I'd prefer to update the modal functionality to match that of docs / drawer component rather than document the inconsistency. Hopefully this will make it into v1.0. Thanks for the catch @jgrayson-apl

**Comment by macandcheese** [comment]
Modal syntax should match that of the drawer component / what's in the docs now: https://github.com/Esri/calcite-web/pull/884/
