### ISSUE TITLE
Change implementation of drawer pattern

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#863]
Having the drawer push the wrapper over creates several problems (on mobile safari, and in preventing the use of `position: sticky` elsewhere on the page.

Should change so that the drawer slides _over_ the wrapper. Make the following changes:

1. remove transitions on wrapper
2. remove `overflow: hidden` declaration on wrapper
3. when drawer opens, add `overflow: hidden` to `html` element (this prevents scrolling in background)

**Comment by paulcpederson** [comment]
will be part of next release

**Comment by asangma** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/1ca6d440-f6ad-4d5d-8044-a86d9a7650c4-cc9a7e17-6cdb-4dbb-94c1-3db902a46cb1-v1.png?transparent=1&palette=1&width=246)
