### ISSUE TITLE
Dark theme switch

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#864]
Currently, there is no way of seeing what dark theme on the documentation page. https://esri.github.io/calcite-web/

Therefore, we need a switch for dark theme.

**Comment by jmdye** [comment]
+1

**Comment by macandcheese** [comment]
A few options for the switch, located the header for visibility... On mobile it will live in the sidebar menu. Basically a single clickable toggle vs. explicit options per theme. Thoughts on a direction?

![options](https://user-images.githubusercontent.com/4733155/36225749-8cdec224-1180-11e8-9aa6-7bbf1370962b.png)

**Comment by jmdye** [comment]
Both look great! I would find the toggle just slightly more intuitive if it were implemented like the Toggle   UI element proposed in #837 . Otherwise, I'd go with the explicit options.

**Comment by julio8a** [comment]
I like the idea of the toggle UI.

We can do something like: `Dark Theme **Toggle**`

**Comment by macandcheese** [comment]
Yeah, I tend to agree that a toggle makes the most sense. Will need to finish https://github.com/Esri/calcite-web/issues/837 first ;)

**Comment by jmdye** [comment]
Can you guys still push forward on #874 separately? I'm eager to get my hands on static dark.css file and I'm just a simpleton.
