### ISSUE TITLE
Avenir Next – Vietnamese

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#865]
from paul:
>took a look at SST and I think it’s much better than what we currently use for Vietnamese. We can simply replace our current Vietnamese stack and use the unicode-range to conditionally load it. 

>Calcite Web handles this by keying off the `lang` attribute on the `html` tag (although this also works for other tags nested within the page). We’ve found this to be a good way to detect that a document is in Vietnamese (`lang=“vi”`) because developers already set this attribute, so they essentially get the correct font without having to do anything.

Replace current Vietnamese solution with SST.

cc'ing: @TheBlueDog, @kyle-03674

**Comment by TheBlueDog** [comment]
Is SST delivered through the same font service?

**Comment by paulcpederson** [comment]
@TheBlueDog yes, I believe so.

**Comment by TheBlueDog** [comment]
@paulcpederson Are the keys and calls for that in Calcite Web files?

**Comment by kyle-03674** [comment]
SST Vietnamese is available on fonts.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__fonts.com&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=BH1IbQAyP2ZYjN-1CD6Lg4RUKlXi4LAplBganHxtnjh1tbdo3N9JUqJpWnrdpkaaKw_Hkt8xnjckwHWh3hbh4CQcGJIGRPyWRssr4EAlkVztP2q6nG8Zduk2e-PBfM3E-5HcBzQ68QBCNB_6IGjU0A&m=SSPF7kCt0X7gSkB28joqXvRuw8ANbrLVHRmNkY6pLOY&s=Kuc-ROhFXJN8RnoJn2Dx8H88dwmReZV-5cSo1mkfCv0&e=>, yes. @paulcpederson<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_paulcpederson&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=3-DJQ2puz88NnBkZzRT6Bu8jrRsr0TX-4-BMQLPkIHU&m=BWvvdNZDVqxPXlF_jiNSwYX-gIDw3Zi_SH-NkPdJAdE&s=nA7beYDaXlP6WYARzCsFAVPoRl1fAtSXuhN0U5CtKLg&e=> can you please add the font as necessary. I’ve never modified the fonts.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__fonts.com&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=BH1IbQAyP2ZYjN-1CD6Lg4RUKlXi4LAplBganHxtnjh1tbdo3N9JUqJpWnrdpkaaKw_Hkt8xnjckwHWh3hbh4CQcGJIGRPyWRssr4EAlkVztP2q6nG8Zduk2e-PBfM3E-5HcBzQ68QBCNB_6IGjU0A&m=SSPF7kCt0X7gSkB28joqXvRuw8ANbrLVHRmNkY6pLOY&s=Kuc-ROhFXJN8RnoJn2Dx8H88dwmReZV-5cSo1mkfCv0&e=> web projects, only the Monotype Enterprise ones.

**Comment by paulcpederson** [comment]
Next release will use SST for Vietnamese.
