### ISSUE TITLE
Improve handling of class modifiers in documentation

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#869]
It would be nice to have a base / modifier paradigm for docs instead of needing to "fake" the base as a modifier with "modifiers: true". Would need to create some logic to display the base example as well as any available modifiers.

**Comment by paulcpederson** [comment]
@macandcheese I think this is a good idea. `modifiers: true` has always felt like a hack.

**Comment by macandcheese** [comment]
Added in https://github.com/Esri/calcite-web/pull/872
