### ISSUE TITLE
Create index / status sheet of components

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#870]
It would be nice to have a quick "at a glance" overview of components available in Calcite, along with implementation status / any other relevant metrics or labels. It should help to more quickly communicate what is available and what's being worked on in Calcite.

Example from vmware's Clarity Design System: https://vmware.github.io/clarity/documentation

**Comment by asangma** [comment]
@macandcheese First off. #bestusername

Secondly, that is all.

**Comment by paulcpederson** [comment]
@macandcheese 👌  

Maybe this could be merged with http://esri.github.io/calcite-web/quick-reference/ ?

**Comment by macandcheese** [comment]
Yep, I think that makes sense to merge with the quick reference sheet in someway.

**Comment by macandcheese** [comment]
Added in https://github.com/Esri/calcite-web/pull/871
