### ISSUE TITLE
Add static files for dark theme

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#874]
Kind of related to #864. there is no way (that I know of) to access the dark theme if you are just using static files. 

On the Color/index.html in Docs, there is a section that indicates the dark theme can be accessed by using ```@import "calcite-web-dark";```. I tried putting that in the console in Chrome - no dice. Also tried adding it to ```all.css``` in Chrome's sources window, but still no luck.

Probably mostly my failure to understand the vast majority of how CW works, but it would be nice if I could access the dark-theme by just loading ```all-dark.css``` file or whatever.

**Comment by paulcpederson** [comment]
related to #864

**Comment by macandcheese** [comment]
Combining with https://github.com/Esri/calcite-web/issues/864 🌱
