### ISSUE TITLE
Add range slider js functionality

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#876]
Moving more advanced js functionality to a separate task to limit the scope of https://github.com/Esri/calcite-web/issues/838.

To include:
- displaying ticks / datalist
- displaying value tooltip
- associating input with range value

**Comment by paulcpederson** [comment]
:+1:

**Comment by macandcheese** [comment]
Since there's no true Chrome support for progress through CSS, will need to add in here as well.
