### ISSUE TITLE
Overuse of !important

### ISSUE THREAD

**Issue by tim-white-esri** [Esri/calcite-web#877]
A quick search of the repo shows that `!important` is used 2,306 times in 20 files. This is not a good practice and presents many challenges when using the framework. We just recently had to increase specificity and add `!important` to a style just to get it to work properly in our instance -- all to override the framework.

**Comment by paulcpederson** [comment]
@tim-white-esri I agree, and I try not to use these unless totally necessary. If you filter by file type scss you can see that in the actual source (`lib`) it only occurs 7 times, so it's not really as hard as fixing it in 2300 places. We can take a look at all of these and make sure they are needed. 

Which in particular gave you trouble?

**Comment by paulcpederson** [comment]
related to the right to left `!important` rules needed to override styles: https://github.com/Esri/calcite-web/issues/805#issuecomment-365457842

**Comment by tim-white-esri** [comment]
@paulcpederson Digging into the issue, part of it is on our end. But looking over the Sass in Calcite, there are still some 20 instances. Looks like a lot are the RTL you've addressed, but there are several others that I don't see why they are there; for example, 
`.center-column {
    margin-left: auto !important; // !important needed to override first column margin (line 34)
    margin-right: auto !important; // !important needed to override last column margin (line 43)
    float: none;
  }`
But the referenced lines (34, 43) don't have `!important` flags on them. 
Additionally, `background-image: url('#{$image-path}/logo/esri-logo.svg') !important;` from the `_esri-logo.scss` file seems very overly specific for something so simple.

**Comment by paulcpederson** [comment]
@tim-white-esri half of those are in the `dist` folder, so it's not 20. 

I agree about the SVG. As I said, we can dig into these and look at them on a case by case basis.

**Comment by tim-white-esri** [comment]
@paulcpederson sounds good. I'll leave it to you.

**Comment by paulcpederson** [comment]
This will be fixed in the next release. Was able to axe a majority of them

**Comment by tim-white-esri** [comment]
Glad to hear it.
