### ISSUE TITLE
Direct links to CDN result in Error

### ISSUE THREAD

**Issue by rralbritton** [Esri/calcite-web#878]
When using the CDN references the webpage fails to open and produces a 'net::ERR_CONTENT_DECODING_FAILED' error.

Issues was tested using the [Quick Start Script](http://esri.github.io/calcite-web/guides/quickstart/) after failing to load my code - same issue resulted. 

The links works individually, but a call is being made to 
[fast.fonts.net](https://fast.fonts.net/t/1.css?apiType=css&projectid=9431e9a5-7a6d-4b5f-82be-4d935972de5a) that is failing.

**Comment by paulcpederson** [comment]
@rralbritton what domain are you using? You must be on a domain that is whitelisted to use the fonts as per our licensing agreement with monotype. 

If you're developing locally, you should add an entry to your hosts file (`private/etc/hosts` on mac) for something like:

```
127.0.0.1       local.arcgis.com
```

That way you can develop your local site by visiting local.arcgis.com in your browser.

**Comment by rralbritton** [comment]
Thanks @paulcpederson . I am developing local in a windows environment. I haven't run into this issue with other ESRI/Calcite  packages in the past.

**Comment by paulcpederson** [comment]
This issue should be fixed in the next release
