### ISSUE TITLE
Style file upload input in Firefox

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#886]
Add brower-specific styling for FF, see below:

![button upload firefox](https://user-images.githubusercontent.com/4733155/37296964-b4a99d20-25d9-11e8-89e1-f2906388b51e.png)

(Chrome / Safari / FF)

**Comment by paulcpederson** [comment]
I'm not sure that firefox gives a pseudo class for styling the file input, IIRC

**Comment by macandcheese** [comment]
Yeah, there's no way to change the button unfortunately. Small improvements https://github.com/Esri/calcite-web/pull/887
