### ISSUE TITLE
Consider reducing default font size to 15px/16px

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#889]
Since launching the REST API docs on the developers site I have gotten numerous bits of feedback about how long the pages are. Mostly this relates to the lack of decent skip links in the REST API pages but JavaScript pages are also pointed to as being excessively long. Most people tend to point to font size as an issue here. For example:

Page | Height (17px) | Height (16px) | Height (14px)
--- | --- | --- | ---
[Route service with synchronous execution](https://developers.arcgis.com/rest/network/api-reference/route-synchronous-service.htm) | 94673px | 87778px (7.28% smaller) | 74259px (21.56% smaller)
[JS API MapView](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#methods-summary) |  65372px | 60967px (6.73% smaller) | 51770px (20.8% smaller)

The UX issues the font size includes are just 1 part of a larger issue for example the [JS API MapView](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#methods-summary) is about 5x longer then [Feature Service Query](https://developers.arcgis.com/rest/services-reference/query-feature-service-.htm#GUID-12F69A26-E600-4F36-9D19-3E931679B4AF) but is vastly easier to navigate because of the skip links.

Calcite Web makes the default body font size 17px ([source](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/type/_styles.scss#L7-L9)) which actually surprised me.  It looks like a few years ago this got bumped up for some reason. Digging into the history it looks like this went through 18 -> 17 -> 16 -> 17 again without any discussion.

The base size being 17px is actually surprising since it means that all of our `rem` measurements are getting rounded. For example `.5rem` is actually `8.5px` which means most browsers will start using sub pixel rendering rather then a whole value. Using `16px` as a base would get us evenly rounded `rem` measurements across the whole site this might be root cause of some IE rounding bugs.

I also looked at other sites to see what the base font size was. It looks like 14px, 15px or 16px I found on 1 site that also used 17px. No site used anything below 14px.

* Google Maps - 16px
* Android Developer - 14px
* Apple Developer - 17px
* MapBox - 15px
* GitHub - 14px
* Carto - 15px
* .Net - 16px

Based on this I'm going to propose reducing the base font size in Calcite Web to either 15px or 16px. Each has some advantages:

* 16px:
  * **PRO** line length is ~90 on pages with both a topic nav and a TOC. Or ~115 on pages with just a topic nav The appears pretty ideal according to this https://www.viget.com/articles/the-line-length-misconception/
  * **PRO** Common `rem` measurements all round evenly.
* 15px
  * **PRO** Big gains in information density, far more text fits into navs and TOCs without wrapping to a second line.
  * **PRO** Good readability at about 95-135 characters per line.
  * **CON** Small text like breadcrumbs, anything in a `<small>` tag or `font-size--2` appears to small at either 13 or 14px.

**Comment by paulcpederson** [comment]
I'd be fine with 16, 15 is too small, though. Several auditing tools actually dock you points if you go below 16px (https://github.com/GoogleChrome/lighthouse/issues/3174).

**Comment by patrickarlt** [comment]
@paulcpederson huh ill have to read those later. 16px it is then! This is probably good to do now before 1.0.0 since it might be a breaking change for some.

**Comment by paulcpederson** [comment]
Yeah this is going to pretty thoroughly break everything as everything is sized off that value. So all the buttons will be smaller, all leader/trailer values will be different, etc

**Comment by patrickarlt** [comment]
@paulcpederson when I was testing this on the Developers site it actually didn't break anything. Some exact pixel measurements might be off but generally everything was ok.

**Comment by paulcpederson** [comment]
16px will be the new base font size as part of the 1.0.0 release.
