### ISSUE TITLE
icon-after and icon-sup modifiers

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#897]
It would be nice to have an additional modifier for ui icons that would move icon placement to after the text rather than before.

For example, the modifier ```icon-ui-link-external``` produces this result when used on an element.
![screen shot 2018-03-21 at 6 21 13 pm](https://user-images.githubusercontent.com/12836703/37740635-cf12af5a-2d34-11e8-9bab-190430431f84.png)

However, if I want that icon to appear after the text rather than before, then I've got to do something like:
```<a class="btn" href="#">See What's New <span class="icon-ui-link-external"></span></a>```

If I want the icon to appear as superscript, the easiest way would be 
```<a class="btn" href="#">See What's New <sup class="icon-ui-link-external"></sup></a>```

Modifiers for icons that facilitated this would be nice.
```<a class="btn icon-ui-link-external icon-after" href="#">See What's New</a>```
![screen shot 2018-03-21 at 6 30 24 pm](https://user-images.githubusercontent.com/12836703/37740965-08df94a4-2d36-11e8-94b2-aba9208fb756.png)

```<a class="btn icon-ui-link-external icon-after icon-sup" href="#">See What's New</a>```
![screen shot 2018-03-21 at 6 30 54 pm](https://user-images.githubusercontent.com/12836703/37740976-10954126-2d36-11e8-8bb6-bebaf31c8fd2.png)

**Comment by paulcpederson** [comment]
The icon font is actually deprecated. You should just put an svg in there.

**Comment by jmdye** [comment]
alrighty then

**Comment by paulcpederson** [comment]
http://gif-finder.com/wp-content/uploads/2016/07/Jim-Carrey-Alrightythen.gif
