### ISSUE TITLE
Toggle requires 3 clicks before "flipping"

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#901]
First off, awesome job on the toggle switch and dark theme. It looks great. I noticed some issues with this first go of it.

After giving the toggle focus with that first click, the clicking the toggle again doesn't actually "flip" the toggle and apply the dark theme. I noticed this only happens if you don't have any cookies or history from CW where the toggle has already been successfully "flipped". If you don't, you have to click on the toggle three times before it flips and the dark theme applies. 

If you have already flipped the toggle once though, then it works as expected so long as you have that history in your browser cache. Clear that history though, and you've got to click on the toggle three times again before it starts working as intended. 

![dark-theme-toggle](https://user-images.githubusercontent.com/12836703/37834903-47071590-2e85-11e8-8379-4e294af9f1a5.gif)
###### Screen Capture: Calcite Web on Safari 11.0.3 running on OSX 10.3.3

I tested the issue on a few different browsers and found it impacted all of the ones I tested with.

- Safari 11.0.3 on OSX 10.13.3
- Safari Mobile on iPhone running iOS 11.2.6
- Chrome 64.0.3282.186 x64 on Windows 7 x64

I did not check to see if the issues appeared on Firefox or Chrome for OSX since I don't have those browsers.

**Comment by macandcheese** [comment]
Will 👀 at this today, thanks.
