### ISSUE TITLE
Accessibility: Allow arrow keys to scroll the sample code box

### ISSUE THREAD

**Issue by jimmieego** [Esri/calcite-web#913]
Sometimes the sample code box needs horizontal/vertical scrolling (e.g., the sample code for [Dropdowns](http://esri.github.io/calcite-web/documentation/components/#dropdowns)). Currently the sample code box is not in tab order (no `tabindex`), which makes it difficult for keyboard users to scroll to see the overflow code. 

Suggestion: 
- Check if the sample code box needs scrolling (using `scrollWidth` and `scrollHeight`?). If yes, add `tabindex = "0"` to the sample code box container so keyboard users can set focus to the sample code and use arrow keys to scroll.
- It's probably not necessary to add `tabindex = "0"` to sample code boxes that do not need to scroll. We can if it's easier to implement.

An example of this accessible pattern: https://thepaciellogroup.github.io/cupper/patterns/coding/code-blocks/. Tab to the sample code boxes in the Annotated code section and you can use arrow keys to scroll.

**Comment by paulcpederson** [comment]
I think we'll just have to add `tabindex=0` to all of them, I don't think that would really have a downside and it would be a LOT easier to implement.

**Comment by jimmieego** [comment]
Totally.

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-web/pull/914 - will update next time we push docs to gh pages.

**Comment by macandcheese** [comment]
Updated on live.
