### ISSUE TITLE
pre- and post- column classes are ignored at wide or high dpi screens

### ISSUE THREAD

**Issue by mpriour** [Esri/calcite-web#923]
The pre and post classes are not getting applied at screen widths larger than 1525px in normal left-to-right layout. They do work properly in rtl mode.
This is likely due to the fact that these classes come before the html selector in the wide screen rules. See: https://github.com/Esri/calcite-web/blob/master/dist/css/calcite-web.css#L1688

**Comment by paulcpederson** [comment]
@mpriour I fixed this on `master` already, will push a new version soon.

**Comment by mpriour** [comment]
@paulcpederson great! thanks.

**Comment by paulcpederson** [comment]
Will keep you posted when the release is out.
