### ISSUE TITLE
Search Overlay broken in Firefox at $phone on Windows

### ISSUE THREAD

**Issue by oknoway** [Esri/calcite-web#932]
Pseudo element used for `vertical-align: middle` is breaking this.

![firefox_2018-04-06_15-05-37](https://user-images.githubusercontent.com/29742178/38446267-f985c136-39ab-11e8-8d15-f103b4246d6a.png)

**Comment by paulcpederson** [comment]
assigning to @oknoway as I believe he's working on a fix right now.

**Comment by paulcpederson** [comment]
will be covered in next release thanks to champion @oknoway
