### ISSUE TITLE
Pricing Table is misaligned with cards in Marketing Extension

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#937]
Not sure what's going on here, but it ain't right. The pricing table looks as if it has a post-3 or 4 applied, but it doesn't. Anyway, the effect is that the table aligns left instead of right. Of course, it's not all bad...

![screen shot 2018-04-10 at 2 39 39 pm](https://user-images.githubusercontent.com/12836703/38577038-ca8a3fea-3ccd-11e8-94ec-5a1bd31bfcb5.png)

**Comment by macandcheese** [comment]
This occurred after the addition of the `table` class, updated docs to fix in https://github.com/Esri/calcite-web/pull/938.
