### ISSUE TITLE
Add extension components to component status table in docs/quick-reference

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#940]
There are additional components in the Navigation and Marketing extensions that are not listed on the component status page in quick-reference. Namely ```.image-switcher```, ```.carousel``` in marketing and ```.pricing-table``` in e-commerce.

Would be nice to be able to see the status of these components there, especially ```. carousel``` since it still seems to be a work in progress.

**Comment by macandcheese** [comment]
Fair enough - we currently only show base library components and not any of our patterns / extensions. Feel free to add those in a PR, or we can try to look at updating that the next pass we do of the Quick Reference section.
