### ISSUE TITLE
Filter dropdown graphics don't support RTL

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-web#941]
Using the example http://esri.github.io/calcite-web/documentation/patterns/#filter-dropdown and adding `dir="rtl"` to the html tag, one sees

![image](https://user-images.githubusercontent.com/2125181/38623080-5db9654c-3d6a-11e8-9dd8-1a2beacd9e24.png)

![image](https://user-images.githubusercontent.com/2125181/38623096-643bf4c0-3d6a-11e8-9f41-4f7f4811ecf8.png)

Adding the following CSS appears to fix this for Chrome 65, Firefox 59, Edge 41, IE 11:

```
html[dir="rtl"] .filter-dropdown-link {
  padding: 0.51667rem 2rem 0.51667rem 1.55rem;
}

html[dir="rtl"] .filter-link-check {
  opacity: 0;
  visibility: hidden;
  margin-top: 6px;
  position: absolute;
  left: auto;  /* for IE11 */
  left: unset;
  right: 9px;
}

html[dir="rtl"] .filter-link-close {
  opacity: 0;
  visibility: hidden;
  margin-top: 6px;
  position: absolute;
  left: 9px;
  right: auto;  /* for IE11 */
  right: unset;
}

html[dir="rtl"] .filter-dropdown-remove .svg-icon {
  left: 0.65em;
}

html[dir="rtl"] .filter-dropdown-active {
  padding: 0.51667rem 0.51667rem 0.51667rem 0;
}
```

![image](https://user-images.githubusercontent.com/2125181/38623228-bfbfbfde-3d6a-11e8-865f-9f876863e47e.png)

![image](https://user-images.githubusercontent.com/2125181/38623215-b69054e6-3d6a-11e8-92f3-a748ed4669da.png)

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-web/pull/942 - also made some slight alignment changes to the filter lists in both RTL and LTR.
