### ISSUE TITLE
Drop shadows on cards

### ISSUE THREAD

**Issue by kylejonesdesign** [Esri/calcite-web#943]
Wanted to see what you all think about providing options for drop shadows on cards. On esri.com for example, we rarely use drop shadows so devs have to manually override this all the time. In our chat on Slack, Adam suggested having options like drop-shadow-small, drop-shadow-medium, drop-shadow-none as opt-in classes that way if teams need to “customize” a component at least it can be selected from a predetermined list.

**Comment by macandcheese** [comment]
Thanks for submitting - This is a good request... In my mind it'll be impossible to have "one size fits all" that will work for everyone, but having some standardized options to choose from could be a good start. I know there have been discussions with @julio8a @mitc7862 etc about creating general Calcite "shadow guidelines" (along with color, spacing, etc)... this is a good example of needing those principles defined...

**Comment by paulcpederson** [comment]
This is similar to what we have with panels. Ie panels have a border by default but we provide a `panel-no-border` modifier to remove it if need be.

**Comment by macandcheese** [comment]
Closing this - will be updated with component UI updates for 2.0
