### ISSUE TITLE
documentation bug – dropdowns

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#944]
dropdown menus are showing up below the code snippets:

![image](https://user-images.githubusercontent.com/6144462/38824963-d866aefa-415f-11e8-8e76-aef42e942c2f.png)

**Comment by macandcheese** [comment]
Yeah, this is a result of trying to constrain full-width component examples like top nav to not break the width of the page, etc... Which doesn't play so nicely with other overflow values. Looking into it...

**Comment by macandcheese** [comment]
Addressed in https://github.com/Esri/calcite-web/pull/946
