### ISSUE TITLE
Opening modal causes page to shift

### ISSUE THREAD

**Issue by skitterm** [Esri/calcite-web#945]
On Windows Chrome, when I open a modal, the page scrollbar goes away and the page shifts ~20px to the right. Otherwise the experience of the modal fading in and up is smooth, but it feels janky when the page shifts quickly underneath it (and then back over when the modal is dismissed).

Would it be possible to keep the scrollbar but still disallow scrolling? Or alternatively, a solution like Bootstrap 4: they remove the scrollbar but the page does not shift: https://getbootstrap.com/docs/4.1/components/modal/

**Comment by paulcpederson** [comment]
Yes, this should be possible with some changes to the `_reset` styles on the html element. The Bootstrap example puts their overflow property on the body element, which I think we should move to. Marking as bug.

**Comment by paulcpederson** [comment]
Will be fixed on next release

**Comment by skitterm** [comment]
Awesome, thanks @paulcpederson!
