### ISSUE TITLE
Accordion closed arrow points in inconsistent direction for RTL

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-web#950]
![image](https://user-images.githubusercontent.com/2125181/39524780-bd297a64-4ddf-11e8-82ab-c9fe45737f73.png) vs. ![image](https://user-images.githubusercontent.com/2125181/39524646-353fc02c-4ddf-11e8-98b4-ca23455a07b2.png)

This CSS fixes it:
```

html[dir="rtl"] .accordion-icon .svg-icon {
  -webkit-transform: rotate(+90deg);
  -moz-transform: rotate(+90deg);
  -ms-transform: rotate(+90deg);
  -o-transform: rotate(+90deg);
  transform: rotate(+90deg);
}
```
![image](https://user-images.githubusercontent.com/2125181/39524688-585207c8-4ddf-11e8-9d98-eaa13e397a18.png)

**Comment by macandcheese** [comment]
Thanks for the catch @MikeTschudi, will be fixed in https://github.com/Esri/calcite-web/pulls
