### ISSUE TITLE
Modals added dynamically take longer and longer to launch

### ISSUE THREAD

**Issue by skitterm** [Esri/calcite-web#954]
I'm working on migrating [My Stories](http://storymaps.arcgis.com/en/my-stories/) from Tailcoat to Calcite . My Stories is a dynamic web app where DOM is added throughout the user's interaction with the page. Some of this added-on-the-fly markup includes buttons that launch modals. Each time I inject these elements, I need to call `calcite.modal()` for the button to get its "launch modal" event. 

However, this means that already-event-listening modal launch buttons get the event added again for each time `calcite.modal()` is called. When I click on such a button, the modal takes more than a second to launch (likely because all of the duplicate modal events on it are firing, and there's a small delay with each event). In the worst cases, it's taking 3-5 seconds to launch the modal after clicking the button 😱 .

The DOM isn't all there at once, so I can't make a singular `calcite.modal()` call and call it a day. Could there be a way to scope the `calcite.modal()` call by doing something like `calcite.modal('.element-selector')`, where all modal buttons within `.element-selector` would get the event to launch a modal?

Alternatively, if there was a `calcite.modal.destroy()` function that unbound all modal event listeners, that would work too.

Repro case with instructions [here](http://jsbin.com/valequyewu/1/edit?html,output).

**Comment by paulcpederson** [comment]
WE have the infrastructure to handle this, we do it in dropdowns already: 

https://github.com/Esri/calcite-web/blob/master/lib/js/patterns/dropdown.js#L47

Just need to write the logic into other patterns. PRs welcome.

**Comment by skitterm** [comment]
Ok, PR submitted to solve this issue.

**Comment by paulcpederson** [comment]
fixed by @skitterm ! Will be part of upcoming release
