### ISSUE TITLE
Is it possible to nudge a font character up a pixel to align it with others?

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-web#957]
The calcite-ui font character \f147 (icon-ui-link-external) is a pixel lower than some of its peers:
![image](https://user-images.githubusercontent.com/2125181/39823147-fb2558fa-5371-11e8-9750-ad0c12c5fa0c.png)

It's not just with these icons; you can see it on the [Calcite icons](http://esri.github.io/calcite-web/documentation/icons/) doc web page:
![image](https://user-images.githubusercontent.com/2125181/39823301-69c49e42-5372-11e8-9bfa-1c53bc1e4183.png)

It would look better, I think, if the box were vertically centered, ignoring the arrow tip.

**Comment by macandcheese** [comment]
Hi Mike - we're in the process of deprecating the icon font - If it's feasible I'd suggest using icons from https://github.com/ArcGIS/calcite-ui-icons library as they actively maintain and update those - the icon folks pretty receptive to icon update suggestions.

**Comment by MikeTschudi** [comment]
Thanks for the link, @macandcheese
