### ISSUE TITLE
li tag

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#962]
I've gotten some feedback from API team about list item tags being difficult to work with since styling is applied to the tag. We had a similar issue with the `table` tag, let's do the same with this `li` tag and  move out styles to class.

**Comment by macandcheese** [comment]
Do you know what version of CW they are using? As of 1.0 there is very minimal styling applied to the base UL / OL classes - a small font scale adjustment. LI elements themselves have a small margin-top adjustment. "Numbered" and "Plain" variants are available via helper class. If you can pass along what the difficulty was that would be helpful.

**Comment by julio8a** [comment]
^ @asangma

**Comment by paulcpederson** [comment]
@julio8a yeah we updated list styles as part of `v1.0.0` to fix #866 . I don't think there is much more we can do, the li styles are largely browser default at this point and there are no nested selectors.

**Comment by paulcpederson** [comment]
I would say tell them to update to the latest and greatest and see if that fixes their issues.

**Comment by asangma** [comment]
[This is the bit](https://github.com/Esri/calcite-web/blob/master/dist/css/calcite-web-no-fonts.css#L2765) that was poking me in the eye.

```
li {
  margin-top: .25em; }
```

But after a chat with @macandcheese, I understand that changing that would break the Internet. For now, we can either fix at the app level or by explicitly setting margins for relevant `li` elements. 

...until we are all one. ☁️

**Comment by julio8a** [comment]
okay, closing this out. Thanks all.
