### ISSUE TITLE
update color variables

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#964]
There is a new colors palette for all of Esri. The new set has matching or close HEX values compared to the old color set. Therefore, updating the colors in CW should not be a major change, but slight color changes at worst.

@paulcpederson, it might be easier to make the adjustments in the [Calcite Color](https://github.com/Esri/calcite-colors) repository since it's referenced by CW?

**Comment by paulcpederson** [comment]
We don't actually pull them in from that repo as it's private and caused problems during installation. We can update them here, though.

**Comment by julio8a** [comment]
@paulcpederson, [calcite-color](https://github.com/Esri/calcite-colors) is public.

**Comment by paulcpederson** [comment]
Nice. We should update all the colors in that repo and then we can pull it into calcite web from there.

**Comment by paulcpederson** [comment]
in progress on 2.0 branch
