### ISSUE TITLE
npm install in documentation fails

### ISSUE THREAD

**Issue by etwood** [Esri/calcite-web#968]
When attempting to install calcite-web using the instructions in the documentation the install fails.

npm install --save-dev Esri/calcite-web#v1.0.1

Tried without the #v1.0.1 and v1.0.2 was installed.

**Comment by macandcheese** [comment]
Hi @etwood - We've updated the docs to reflect the current release. Let me know if you have any further issues.

**Comment by paulcpederson** [comment]
@etwood feel free to reopen if you issue was not addressed!

**Comment by etwood** [comment]
Thanks for the quick response.  I double checked and it looks good.
