### ISSUE TITLE
calcite-ui-icons integration

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#974]
* We need to bring in the new svg icons from the [calcite-ui-icon repository](https://github.com/Esri/calcite-ui-icons) and deprecate the old CW icons.
* Additionally, we'll need a reference page where all the icons are displayed. Similar to what we were doing on clidev:
![image](https://user-images.githubusercontent.com/6144462/43925466-27b3548c-9bdc-11e8-9de8-60f630b49cf6.png)

The sooner we get the reference page up the better, since people who are using the public repo need to visualize the icons from calcite-ui-icons public repository.

**Comment by paulcpederson** [comment]
Calcite UI Icons has it's own preview site now: https://esri.github.io/calcite-ui-icons/

The icons are integrated and displayed in the `2.0` branch, so I am closing this issue. 👍
