### ISSUE TITLE
Publish on NPM catalog

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#976]
https://www.npmjs.com/search?q=calcite

**Comment by schontz** [comment]
Until then, the [npm installation instructions](http://esri.github.io/calcite-web/documentation/#npm) do not work!

**Comment by paulcpederson** [comment]
@schontz actually those instructions will work. That is the syntax for installing an npm module via a _GitHub repository_. So that has and will continue to work even without publishing.

**Comment by schontz** [comment]
OK. But FYI...

```
> npm i -D Esri/calcite-web#1.1.0
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout 1.1.0
npm ERR! error: pathspec '1.1.0' did not match any file(s) known to git.
```

**Comment by paulcpederson** [comment]
@schontz oh, you're missing the `v` on the version name, should be `#v1.1.0` as per the documentation. Just tried on Windows and it works fine.

**Comment by schontz** [comment]
Oops. Thank you!

**Comment by macandcheese** [comment]
The Calcite Web project is deprecated, closing.
