### ISSUE TITLE
Input type "date" not working in IE11

### ISSUE THREAD

**Issue by ialixandroae** [Esri/calcite-web#988]
The date picker in input type "date" not appearing in IE11.
The behavior is like a normal input type "text" 

![image](https://user-images.githubusercontent.com/18401030/46785292-02964580-cd3a-11e8-8b8a-aabbf41ab306.png)

**Comment by paulcpederson** [comment]
Unfortunately that's a limitation of IE11. We are styling the HTML5 element, but IE11 doesn't provide it: https://caniuse.com/#feat=input-datetime .

I believe there are polyfills for IE11 that replicate that behavior, and there are also several third-party date selection widgets. Hope that helps...

**Comment by ialixandroae** [comment]
Oh, ok... well, I will see what I can do about this.
Thanks a lot for your feedback!
