### ISSUE TITLE
Avenir Next – esri MLA license (Typography docs)

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#997]
We need to guide users on who can and can not use Avenir Next through Calcite-Web.
We need to point them to the section in Esri's MLA to identify if they qualify for usage. 

https://www.esri.com/en-us/legal/terms/full-master-agreement/mla-e204-e300-english
Master Agreement > 2.0 Software > 2.2 Permitted Uses > section C.

**Comment by paulcpederson** [comment]
will be deployed to doc site after 1.2.0 gets released
