### ISSUE TITLE
tabs-vertical modifier

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#999]
Can I haz a tabs-vertical modifier that would display the tabs in a vertical stack on the left side of the screen? Please! I'll give you a :cookie:

**Comment by paulcpederson** [comment]
@jmdye you could maybe use a view-switcher for this: http://esri.github.io/calcite-web/examples/marketing/

It's from the marketing extension, so requires another css/js file

**Comment by jmdye** [comment]
that could probably work
